"""Views and Indexes Consolidated

Revision ID: 0004
Revises: 0003
Create Date: 2024-05-08 18:35:00.000000

"""
from typing import Sequence, Union
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ca_biositing.landiq_record_view
    op.execute("""
        CREATE MATERIALIZED VIEW ca_biositing.landiq_record_view AS
        SELECT landiq_record.record_id, polygon.geom AS geom, polygon.geoid, primary_ag_product.name AS crop_name, landiq_record.acres, landiq_record.irrigated, landiq_record.confidence, landiq_record.dataset_id
FROM landiq_record JOIN polygon ON landiq_record.polygon_id = polygon.id JOIN primary_ag_product ON landiq_record.main_crop = primary_ag_product.id
    """)
    # ca_biositing.landiq_tileset_view
    op.execute("""
        CREATE MATERIALIZED VIEW ca_biositing.landiq_tileset_view AS
        SELECT landiq_record.id, polygon.geom AS geom, primary_ag_product.name AS main_crop, landiq_record.acres, landiq_record.county, polygon.geoid, landiq_record.dataset_id AS tileset_id
FROM landiq_record JOIN polygon ON landiq_record.polygon_id = polygon.id JOIN primary_ag_product ON landiq_record.main_crop = primary_ag_product.id
    """)
    # ca_biositing.analysis_data_view
    op.execute("""
        CREATE MATERIALIZED VIEW ca_biositing.analysis_data_view AS
        SELECT observation.id, observation.record_id, observation.record_type, resource.id AS resource_id, lower(resource.name) AS resource, location_address.geography_id AS geoid, lower(parameter.name) AS parameter, observation.value, lower(unit.name) AS unit, lower(dimension_type.name) AS dimension, observation.dimension_value, lower(analysis_du.name) AS dimension_unit
FROM observation JOIN parameter ON observation.parameter_id = parameter.id JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN dimension_type ON observation.dimension_type_id = dimension_type.id LEFT OUTER JOIN unit AS analysis_du ON observation.dimension_unit_id = analysis_du.id LEFT OUTER JOIN proximate_record ON lower(observation.record_id) = lower(proximate_record.record_id) AND lower(observation.record_type) IN ('proximate analysis', 'proximate_analysis') LEFT OUTER JOIN ultimate_record ON lower(observation.record_id) = lower(ultimate_record.record_id) AND lower(observation.record_type) IN ('ultimate analysis', 'ultimate_analysis') LEFT OUTER JOIN compositional_record ON lower(observation.record_id) = lower(compositional_record.record_id) AND lower(observation.record_type) IN ('compositional analysis', 'compositional_analysis') LEFT OUTER JOIN icp_record ON lower(observation.record_id) = lower(icp_record.record_id) AND (lower(observation.record_type) = 'icp analysis' OR lower(observation.record_type) = 'icp_analysis' OR lower(observation.record_type) = 'icp-oes' OR lower(observation.record_type) = 'icp-ms') LEFT OUTER JOIN xrf_record ON lower(observation.record_id) = lower(xrf_record.record_id) AND lower(observation.record_type) IN ('xrf analysis', 'xrf_analysis') LEFT OUTER JOIN calorimetry_record ON lower(observation.record_id) = lower(calorimetry_record.record_id) AND lower(observation.record_type) IN ('calorimetry analysis', 'calorimetry_analysis') LEFT OUTER JOIN xrd_record ON lower(observation.record_id) = lower(xrd_record.record_id) AND lower(observation.record_type) IN ('xrd analysis', 'xrd_analysis') LEFT OUTER JOIN fermentation_record ON lower(observation.record_id) = lower(fermentation_record.record_id) AND lower(observation.record_type) = 'fermentation' LEFT OUTER JOIN pretreatment_record ON lower(observation.record_id) = lower(pretreatment_record.record_id) AND lower(observation.record_type) = 'pretreatment' LEFT OUTER JOIN prepared_sample ON prepared_sample.id = coalesce(proximate_record.prepared_sample_id, ultimate_record.prepared_sample_id, compositional_record.prepared_sample_id, icp_record.prepared_sample_id, xrf_record.prepared_sample_id, calorimetry_record.prepared_sample_id, xrd_record.prepared_sample_id, fermentation_record.prepared_sample_id, pretreatment_record.prepared_sample_id) LEFT OUTER JOIN field_sample ON field_sample.id = prepared_sample.field_sample_id LEFT OUTER JOIN resource ON resource.id = coalesce(proximate_record.resource_id, ultimate_record.resource_id, compositional_record.resource_id, icp_record.resource_id, xrf_record.resource_id, calorimetry_record.resource_id, xrd_record.resource_id, fermentation_record.resource_id, pretreatment_record.resource_id, field_sample.resource_id) LEFT OUTER JOIN location_address ON location_address.id = field_sample.sampling_location_id
WHERE (lower(observation.record_type) NOT IN ('usda_census_record', 'usda_survey_record'))
    """)
    # ca_biositing.usda_census_view
    op.execute("""
        CREATE MATERIALIZED VIEW ca_biositing.usda_census_view AS
        SELECT observation.id, lower(usda_commodity.api_name) AS usda_crop, place.geoid, lower(parameter.name) AS parameter, observation.value, lower(unit.name) AS unit, lower(dimension_type.name) AS dimension, observation.dimension_value, lower(du.name) AS dimension_unit, usda_commodity.id AS commodity_id, usda_census_record.id AS source_record_id, usda_census_record.year AS record_year
FROM observation JOIN usda_census_record ON observation.record_id = CAST(usda_census_record.id AS VARCHAR) AND observation.record_type = 'usda_census_record' JOIN usda_commodity ON usda_census_record.commodity_code = usda_commodity.id JOIN place ON usda_census_record.geoid = place.geoid JOIN parameter ON observation.parameter_id = parameter.id JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN dimension_type ON observation.dimension_type_id = dimension_type.id LEFT OUTER JOIN unit AS du ON observation.dimension_unit_id = du.id
    """)
    # ca_biositing.usda_survey_view
    op.execute("""
        CREATE MATERIALIZED VIEW ca_biositing.usda_survey_view AS
        SELECT observation.id, lower(usda_commodity.api_name) AS usda_crop, place.geoid, lower(parameter.name) AS parameter, observation.value, lower(unit.name) AS unit, lower(dimension_type.name) AS dimension, observation.dimension_value, lower(du.name) AS dimension_unit, usda_commodity.id AS commodity_id, usda_survey_record.id AS source_record_id, usda_survey_record.year AS record_year, usda_survey_record.survey_program_id, usda_survey_record.survey_period, usda_survey_record.reference_month, usda_survey_record.seasonal_flag
FROM observation JOIN usda_survey_record ON observation.record_id = CAST(usda_survey_record.id AS VARCHAR) AND observation.record_type = 'usda_survey_record' JOIN usda_commodity ON usda_survey_record.commodity_code = usda_commodity.id JOIN place ON usda_survey_record.geoid = place.geoid JOIN parameter ON observation.parameter_id = parameter.id JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN dimension_type ON observation.dimension_type_id = dimension_type.id LEFT OUTER JOIN unit AS du ON observation.dimension_unit_id = du.id
    """)
    # ca_biositing.usda_resource_commodity_view
    op.execute("""
        CREATE MATERIALIZED VIEW ca_biositing.usda_resource_commodity_view AS
        SELECT resource.name AS resource, resource_usda_commodity_map.usda_commodity_id AS commodity_id
FROM resource JOIN resource_usda_commodity_map ON resource_usda_commodity_map.resource_id = resource.id
WHERE resource_usda_commodity_map.usda_commodity_id IS NOT NULL AND resource.name IS NOT NULL
    """)
    # ca_biositing.billion_ton_tileset_view
    op.execute("""
        CREATE MATERIALIZED VIEW ca_biositing.billion_ton_tileset_view AS
        SELECT billion_ton2023_record.id, resource.name AS resource, lower(place.county_name) AS county, 'production' AS parameter, CAST(billion_ton2023_record.production AS FLOAT) AS value, lower(unit.name) AS unit, billion_ton2023_record.etl_run_id AS tileset_id
FROM billion_ton2023_record JOIN resource ON billion_ton2023_record.resource_id = resource.id JOIN place ON billion_ton2023_record.geoid = place.geoid JOIN unit ON billion_ton2023_record.production_unit_id = unit.id
    """)
    # ca_biositing.analysis_average_view
    op.execute("""
        CREATE MATERIALIZED VIEW ca_biositing.analysis_average_view AS

    SELECT resource, geoid, parameter,
           AVG(value) as average_value,
           STDDEV(value) as standard_deviation,
           unit, COUNT(*) as observation_count
    FROM ca_biositing.analysis_data_view
    GROUP BY resource, geoid, parameter, unit

    """)
    # data_portal.mv_biomass_availability
    op.execute("""
        CREATE MATERIALIZED VIEW data_portal.mv_biomass_availability AS
        SELECT resource.id AS resource_id, resource.name AS resource_name, min(resource_availability.from_month) AS from_month, max(resource_availability.to_month) AS to_month, bool_or(resource_availability.year_round) AS year_round, avg(resource_availability.residue_factor_dry_tons_acre) AS dry_tons_per_acre, avg(resource_availability.residue_factor_wet_tons_acre) AS wet_tons_per_acre
FROM resource_availability JOIN resource ON resource_availability.resource_id = resource.id GROUP BY resource.id, resource.name
    """)
    # data_portal.mv_biomass_volume_estimate
    op.execute("""
        CREATE MATERIALIZED VIEW data_portal.mv_biomass_volume_estimate AS
        SELECT row_number() OVER (ORDER BY anon_1.resource_id, anon_1.geoid, anon_1.dataset_year, anon_1.volume_source) AS id, anon_1.resource_id, anon_1.resource_name, anon_1.geoid, anon_1.county, anon_1.state, anon_1.dataset_year, anon_1.primary_product_volume AS production_volume, anon_1.county_crop_acres, anon_1.volume_unit AS production_unit, anon_1.factor_min, anon_1.factor_mid, anon_1.factor_max, anon_1.estimated_residue_volume_min, anon_1.estimated_residue_volume_mid, anon_1.estimated_residue_volume_max, anon_1.volume_source, anon_1.biomass_unit
FROM (SELECT resource.id AS resource_id, resource.name AS resource_name, county_ag_report_record.geoid AS geoid, place.county_name AS county, place.state_name AS state, county_ag_report_record.data_year AS dataset_year, county_ag_report_record.record_id AS record_id, avg(CASE WHEN (parameter.name = 'production') THEN observation.value END) AS primary_product_volume, avg(CASE WHEN (parameter.name = 'harvested acres') THEN observation.value END) AS county_crop_acres, max(CASE WHEN (parameter.name = 'production') THEN unit.name END) AS volume_unit, residue_factor.factor_min AS factor_min, residue_factor.factor_mid AS factor_mid, residue_factor.factor_max AS factor_max, avg(CASE WHEN (parameter.name = 'production') THEN observation.value END) * residue_factor.factor_min AS estimated_residue_volume_min, avg(CASE WHEN (parameter.name = 'production') THEN observation.value END) * residue_factor.factor_mid AS estimated_residue_volume_mid, avg(CASE WHEN (parameter.name = 'production') THEN observation.value END) * residue_factor.factor_max AS estimated_residue_volume_max, 'production_based' AS volume_source, 'dry_tons' AS biomass_unit
FROM county_ag_report_record JOIN resource ON county_ag_report_record.primary_ag_product_id = resource.primary_ag_product_id JOIN residue_factor ON residue_factor.resource_id = resource.id JOIN place ON county_ag_report_record.geoid = place.geoid LEFT OUTER JOIN observation ON observation.record_id = county_ag_report_record.record_id AND observation.record_type = 'county_ag_report_record' LEFT OUTER JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id
WHERE residue_factor.factor_type = 'weight' AND county_ag_report_record.data_year >= 2017 GROUP BY resource.id, resource.name, county_ag_report_record.geoid, place.county_name, place.state_name, county_ag_report_record.data_year, county_ag_report_record.record_id, residue_factor.factor_min, residue_factor.factor_mid, residue_factor.factor_max) AS anon_1 UNION ALL SELECT row_number() OVER (ORDER BY anon_2.resource_id, anon_2.geoid, anon_2.dataset_year, anon_2.volume_source) AS id, anon_2.resource_id, anon_2.resource_name, anon_2.geoid, anon_2.county, anon_2.state, anon_2.dataset_year, anon_2.bearing_acres AS production_volume, anon_2.county_crop_acres, anon_2.volume_unit AS production_unit, NULL AS factor_min, NULL AS factor_mid, NULL AS factor_max, anon_2.estimated_residue_volume_min, anon_2.estimated_residue_volume_mid, anon_2.estimated_residue_volume_max, anon_2.volume_source, anon_2.biomass_unit
FROM (SELECT resource.id AS resource_id, resource.name AS resource_name, usda_census_record.geoid AS geoid, place.county_name AS county, place.state_name AS state, usda_census_record.year AS dataset_year, usda_census_record.id AS record_id, avg(observation.value) AS bearing_acres, avg(observation.value) AS county_crop_acres, 'acres' AS volume_unit, residue_factor.prune_trim_yield AS prune_trim_yield, residue_factor.prune_trim_yield_unit_id AS prune_trim_yield_unit_id, max(unit.name) AS yield_unit, avg(observation.value) * residue_factor.prune_trim_yield AS estimated_residue_volume_min, avg(observation.value) * residue_factor.prune_trim_yield AS estimated_residue_volume_mid, avg(observation.value) * residue_factor.prune_trim_yield AS estimated_residue_volume_max, 'census_bearing_acres' AS volume_source, 'dry_tons' AS biomass_unit
FROM usda_census_record JOIN usda_commodity ON usda_census_record.commodity_code = usda_commodity.id JOIN resource_usda_commodity_map ON resource_usda_commodity_map.usda_commodity_id = usda_commodity.id JOIN resource ON resource.id = resource_usda_commodity_map.resource_id JOIN residue_factor ON residue_factor.resource_id = resource.id JOIN place ON usda_census_record.geoid = place.geoid LEFT OUTER JOIN observation ON observation.record_id = CAST(usda_census_record.id AS VARCHAR) AND observation.record_type = 'usda_census_record' LEFT OUTER JOIN unit ON residue_factor.prune_trim_yield_unit_id = unit.id
WHERE residue_factor.prune_trim_yield IS NOT NULL AND usda_census_record.year >= 2017 GROUP BY resource.id, resource.name, usda_census_record.geoid, place.county_name, place.state_name, usda_census_record.year, usda_census_record.id, residue_factor.prune_trim_yield, residue_factor.prune_trim_yield_unit_id) AS anon_2
    """)
    # data_portal.mv_biomass_search
    op.execute("""
        CREATE MATERIALIZED VIEW data_portal.mv_biomass_search AS
        SELECT resource.id, resource.name, resource.resource_code, resource.description, resource_class.name AS resource_class, resource_subclass.name AS resource_subclass, coalesce(primary_ag_product.name, anon_1.primary_product_fallback) AS primary_product, resource_morphology.morphology_uri AS image_url, resource.uri AS literature_uri, anon_2.total_annual_volume, anon_2.county_count, anon_2.volume_unit, anon_3.moisture_percent, anon_3.sugar_content_percent, anon_3.glucan_percent, anon_3.xylan_percent, anon_3.ash_percent, anon_3.lignin_percent, anon_3.carbon_percent, anon_3.hydrogen_percent, anon_3.cn_ratio, anon_4.transport_notes, anon_5.storage_notes, coalesce(anon_6.tags, CAST(ARRAY[] AS VARCHAR[])) AS tags, anon_7.from_month AS season_from_month, anon_7.to_month AS season_to_month, anon_7.year_round, coalesce(anon_3.has_proximate, false) AS has_proximate, coalesce(anon_3.has_compositional, false) AS has_compositional, coalesce(anon_3.has_ultimate, false) AS has_ultimate, coalesce(anon_3.has_xrf, false) AS has_xrf, coalesce(anon_3.has_icp, false) AS has_icp, coalesce(anon_3.has_calorimetry, false) AS has_calorimetry, coalesce(anon_3.has_xrd, false) AS has_xrd, coalesce(anon_3.has_ftnir, false) AS has_ftnir, coalesce(anon_3.has_fermentation, false) AS has_fermentation, coalesce(anon_3.has_gasification, false) AS has_gasification, coalesce(anon_3.has_pretreatment, false) AS has_pretreatment, CASE WHEN (anon_3.moisture_percent IS NOT NULL) THEN true ELSE false END AS has_moisture_data, CASE WHEN (anon_3.sugar_content_percent > 0) THEN true ELSE false END AS has_sugar_data, CASE WHEN (resource_morphology.morphology_uri IS NOT NULL) THEN true ELSE false END AS has_image, CASE WHEN (anon_2.total_annual_volume IS NOT NULL) THEN true ELSE false END AS has_volume_data, anon_8.calculated_estimate_volume_min, anon_8.calculated_estimate_volume_max, anon_8.calculated_estimate_volume_mid, resource.created_at, resource.updated_at, to_tsvector('english', coalesce(resource.name, '') || ' ' || coalesce(resource.description, '') || ' ' || coalesce(resource_class.name, '') || ' ' || coalesce(resource_subclass.name, '') || ' ' || coalesce(coalesce(primary_ag_product.name, anon_1.primary_product_fallback), '')) AS search_vector
FROM resource LEFT OUTER JOIN resource_class ON resource.resource_class_id = resource_class.id LEFT OUTER JOIN resource_subclass ON resource.resource_subclass_id = resource_subclass.id LEFT OUTER JOIN primary_ag_product ON resource.primary_ag_product_id = primary_ag_product.id LEFT OUTER JOIN (SELECT resource_usda_commodity_map.resource_id AS resource_id, max(primary_ag_product.name) AS primary_product_fallback
FROM resource_usda_commodity_map JOIN primary_ag_product ON resource_usda_commodity_map.primary_ag_product_id = primary_ag_product.id
WHERE resource_usda_commodity_map.resource_id IS NOT NULL GROUP BY resource_usda_commodity_map.resource_id) AS anon_1 ON anon_1.resource_id = resource.id LEFT OUTER JOIN resource_morphology ON resource_morphology.resource_id = resource.id LEFT OUTER JOIN (SELECT billion_ton2023_record.resource_id AS resource_id, sum(billion_ton2023_record.production) AS total_annual_volume, count(distinct(billion_ton2023_record.geoid)) AS county_count, max(unit.name) AS volume_unit
FROM billion_ton2023_record JOIN unit ON billion_ton2023_record.production_unit_id = unit.id GROUP BY billion_ton2023_record.resource_id) AS anon_2 ON anon_2.resource_id = resource.id LEFT OUTER JOIN (SELECT anon_9.resource_id AS resource_id, sum(anon_9.estimated_residue_volume_min) AS calculated_estimate_volume_min, sum(anon_9.estimated_residue_volume_max) AS calculated_estimate_volume_max, sum(anon_9.estimated_residue_volume_mid) AS calculated_estimate_volume_mid
FROM (SELECT row_number() OVER (ORDER BY anon_10.resource_id, anon_10.geoid, anon_10.dataset_year, anon_10.volume_source) AS id, anon_10.resource_id AS resource_id, anon_10.resource_name AS resource_name, anon_10.geoid AS geoid, anon_10.county AS county, anon_10.state AS state, anon_10.dataset_year AS dataset_year, anon_10.primary_product_volume AS production_volume, anon_10.county_crop_acres AS county_crop_acres, anon_10.volume_unit AS production_unit, anon_10.factor_min AS factor_min, anon_10.factor_mid AS factor_mid, anon_10.factor_max AS factor_max, anon_10.estimated_residue_volume_min AS estimated_residue_volume_min, anon_10.estimated_residue_volume_mid AS estimated_residue_volume_mid, anon_10.estimated_residue_volume_max AS estimated_residue_volume_max, anon_10.volume_source AS volume_source, anon_10.biomass_unit AS biomass_unit
FROM (SELECT resource.id AS resource_id, resource.name AS resource_name, county_ag_report_record.geoid AS geoid, place.county_name AS county, place.state_name AS state, county_ag_report_record.data_year AS dataset_year, county_ag_report_record.record_id AS record_id, avg(CASE WHEN (parameter.name = 'production') THEN observation.value END) AS primary_product_volume, avg(CASE WHEN (parameter.name = 'harvested acres') THEN observation.value END) AS county_crop_acres, max(CASE WHEN (parameter.name = 'production') THEN unit.name END) AS volume_unit, residue_factor.factor_min AS factor_min, residue_factor.factor_mid AS factor_mid, residue_factor.factor_max AS factor_max, avg(CASE WHEN (parameter.name = 'production') THEN observation.value END) * residue_factor.factor_min AS estimated_residue_volume_min, avg(CASE WHEN (parameter.name = 'production') THEN observation.value END) * residue_factor.factor_mid AS estimated_residue_volume_mid, avg(CASE WHEN (parameter.name = 'production') THEN observation.value END) * residue_factor.factor_max AS estimated_residue_volume_max, 'production_based' AS volume_source, 'dry_tons' AS biomass_unit
FROM county_ag_report_record JOIN resource ON county_ag_report_record.primary_ag_product_id = resource.primary_ag_product_id JOIN residue_factor ON residue_factor.resource_id = resource.id JOIN place ON county_ag_report_record.geoid = place.geoid LEFT OUTER JOIN observation ON observation.record_id = county_ag_report_record.record_id AND observation.record_type = 'county_ag_report_record' LEFT OUTER JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id
WHERE residue_factor.factor_type = 'weight' AND county_ag_report_record.data_year >= 2017 GROUP BY resource.id, resource.name, county_ag_report_record.geoid, place.county_name, place.state_name, county_ag_report_record.data_year, county_ag_report_record.record_id, residue_factor.factor_min, residue_factor.factor_mid, residue_factor.factor_max) AS anon_10 UNION ALL SELECT row_number() OVER (ORDER BY anon_11.resource_id, anon_11.geoid, anon_11.dataset_year, anon_11.volume_source) AS id, anon_11.resource_id AS resource_id, anon_11.resource_name AS resource_name, anon_11.geoid AS geoid, anon_11.county AS county, anon_11.state AS state, anon_11.dataset_year AS dataset_year, anon_11.bearing_acres AS production_volume, anon_11.county_crop_acres AS county_crop_acres, anon_11.volume_unit AS production_unit, NULL AS factor_min, NULL AS factor_mid, NULL AS factor_max, anon_11.estimated_residue_volume_min AS estimated_residue_volume_min, anon_11.estimated_residue_volume_mid AS estimated_residue_volume_mid, anon_11.estimated_residue_volume_max AS estimated_residue_volume_max, anon_11.volume_source AS volume_source, anon_11.biomass_unit AS biomass_unit
FROM (SELECT resource.id AS resource_id, resource.name AS resource_name, usda_census_record.geoid AS geoid, place.county_name AS county, place.state_name AS state, usda_census_record.year AS dataset_year, usda_census_record.id AS record_id, avg(observation.value) AS bearing_acres, avg(observation.value) AS county_crop_acres, 'acres' AS volume_unit, residue_factor.prune_trim_yield AS prune_trim_yield, residue_factor.prune_trim_yield_unit_id AS prune_trim_yield_unit_id, max(unit.name) AS yield_unit, avg(observation.value) * residue_factor.prune_trim_yield AS estimated_residue_volume_min, avg(observation.value) * residue_factor.prune_trim_yield AS estimated_residue_volume_mid, avg(observation.value) * residue_factor.prune_trim_yield AS estimated_residue_volume_max, 'census_bearing_acres' AS volume_source, 'dry_tons' AS biomass_unit
FROM usda_census_record JOIN usda_commodity ON usda_census_record.commodity_code = usda_commodity.id JOIN resource_usda_commodity_map ON resource_usda_commodity_map.usda_commodity_id = usda_commodity.id JOIN resource ON resource.id = resource_usda_commodity_map.resource_id JOIN residue_factor ON residue_factor.resource_id = resource.id JOIN place ON usda_census_record.geoid = place.geoid LEFT OUTER JOIN observation ON observation.record_id = CAST(usda_census_record.id AS VARCHAR) AND observation.record_type = 'usda_census_record' LEFT OUTER JOIN unit ON residue_factor.prune_trim_yield_unit_id = unit.id
WHERE residue_factor.prune_trim_yield IS NOT NULL AND usda_census_record.year >= 2017 GROUP BY resource.id, resource.name, usda_census_record.geoid, place.county_name, place.state_name, usda_census_record.year, usda_census_record.id, residue_factor.prune_trim_yield, residue_factor.prune_trim_yield_unit_id) AS anon_11) AS anon_9
WHERE anon_9.dataset_year = 2024 GROUP BY anon_9.resource_id) AS anon_8 ON anon_8.resource_id = resource.id LEFT OUTER JOIN (SELECT anon_12.resource_id AS resource_id, avg(CASE WHEN (anon_13.parameter = 'moisture') THEN anon_13.value END) AS moisture_percent, avg(CASE WHEN (anon_13.parameter = 'ash') THEN anon_13.value END) AS ash_percent, CASE WHEN (avg(CASE WHEN (anon_13.parameter = 'lignin') THEN anon_13.value END) IS NOT NULL OR avg(CASE WHEN (anon_13.parameter = 'lignin+') THEN anon_13.value END) IS NOT NULL) THEN coalesce(avg(CASE WHEN (anon_13.parameter = 'lignin') THEN anon_13.value END), 0) + coalesce(avg(CASE WHEN (anon_13.parameter = 'lignin+') THEN anon_13.value END), 0) END AS lignin_percent, CASE WHEN (avg(CASE WHEN (anon_13.parameter = 'glucose') THEN anon_13.value END) IS NOT NULL OR avg(CASE WHEN (anon_13.parameter = 'xylose') THEN anon_13.value END) IS NOT NULL) THEN coalesce(avg(CASE WHEN (anon_13.parameter = 'glucose') THEN anon_13.value END), 0) + coalesce(avg(CASE WHEN (anon_13.parameter = 'xylose') THEN anon_13.value END), 0) END AS sugar_content_percent, avg(CASE WHEN (anon_13.parameter = 'glucose') THEN anon_13.value END) AS glucan_percent, avg(CASE WHEN (anon_13.parameter = 'xylose') THEN anon_13.value END) AS xylan_percent, avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'carbon') THEN anon_13.value END) AS carbon_percent, avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'hydrogen') THEN anon_13.value END) AS hydrogen_percent, CASE WHEN (avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'carbon') THEN anon_13.value END) IS NOT NULL AND avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'nitrogen') THEN anon_13.value END) IS NOT NULL AND avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'nitrogen') THEN anon_13.value END) != 0) THEN avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'carbon') THEN anon_13.value END) / CAST(CAST(avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'nitrogen') THEN anon_13.value END) AS NUMERIC) AS NUMERIC) END AS cn_ratio, bool_or(anon_12.type = 'proximate analysis') AS has_proximate, bool_or(anon_12.type = 'compositional analysis') AS has_compositional, bool_or(anon_12.type = 'ultimate analysis') AS has_ultimate, bool_or(anon_12.type = 'xrf analysis') AS has_xrf, bool_or(anon_12.type = 'icp analysis') AS has_icp, bool_or(anon_12.type = 'calorimetry analysis') AS has_calorimetry, bool_or(anon_12.type = 'xrd analysis') AS has_xrd, bool_or(anon_12.type = 'ftnir analysis') AS has_ftnir, bool_or(anon_12.type = 'fermentation') AS has_fermentation, bool_or(anon_12.type = 'gasification') AS has_gasification, bool_or(anon_12.type = 'pretreatment') AS has_pretreatment
FROM (SELECT CAST(compositional_record.resource_id AS INTEGER) AS resource_id, CAST(compositional_record.record_id AS VARCHAR) AS record_id, 'compositional analysis' AS type
FROM compositional_record
WHERE compositional_record.qc_pass != 'fail' UNION ALL SELECT CAST(proximate_record.resource_id AS INTEGER) AS resource_id, CAST(proximate_record.record_id AS VARCHAR) AS record_id, 'proximate analysis' AS anon_14
FROM proximate_record
WHERE proximate_record.qc_pass != 'fail' UNION ALL SELECT CAST(ultimate_record.resource_id AS INTEGER) AS resource_id, CAST(ultimate_record.record_id AS VARCHAR) AS record_id, 'ultimate analysis' AS anon_15
FROM ultimate_record
WHERE ultimate_record.qc_pass != 'fail' UNION ALL SELECT CAST(xrf_record.resource_id AS INTEGER) AS resource_id, CAST(xrf_record.record_id AS VARCHAR) AS record_id, 'xrf analysis' AS anon_16
FROM xrf_record
WHERE xrf_record.qc_pass != 'fail' UNION ALL SELECT CAST(icp_record.resource_id AS INTEGER) AS resource_id, CAST(icp_record.record_id AS VARCHAR) AS record_id, 'icp analysis' AS anon_17
FROM icp_record
WHERE icp_record.qc_pass != 'fail' UNION ALL SELECT CAST(calorimetry_record.resource_id AS INTEGER) AS resource_id, CAST(calorimetry_record.record_id AS VARCHAR) AS record_id, 'calorimetry analysis' AS anon_18
FROM calorimetry_record
WHERE calorimetry_record.qc_pass != 'fail' UNION ALL SELECT CAST(xrd_record.resource_id AS INTEGER) AS resource_id, CAST(xrd_record.record_id AS VARCHAR) AS record_id, 'xrd analysis' AS anon_19
FROM xrd_record
WHERE xrd_record.qc_pass != 'fail' UNION ALL SELECT CAST(ftnir_record.resource_id AS INTEGER) AS resource_id, CAST(ftnir_record.record_id AS VARCHAR) AS record_id, 'ftnir analysis' AS anon_20
FROM ftnir_record
WHERE ftnir_record.qc_pass != 'fail' UNION ALL SELECT CAST(fermentation_record.resource_id AS INTEGER) AS resource_id, CAST(fermentation_record.record_id AS VARCHAR) AS record_id, 'fermentation' AS anon_21
FROM fermentation_record
WHERE fermentation_record.qc_pass != 'fail' UNION ALL SELECT CAST(gasification_record.resource_id AS INTEGER) AS resource_id, CAST(gasification_record.record_id AS VARCHAR) AS record_id, 'gasification' AS anon_22
FROM gasification_record
WHERE gasification_record.qc_pass != 'fail' UNION ALL SELECT CAST(pretreatment_record.resource_id AS INTEGER) AS resource_id, CAST(pretreatment_record.record_id AS VARCHAR) AS record_id, 'pretreatment' AS anon_23
FROM pretreatment_record
WHERE pretreatment_record.qc_pass != 'fail') AS anon_12 LEFT OUTER JOIN (SELECT CAST(observation.record_id AS VARCHAR) AS record_id, CAST(observation.record_type AS VARCHAR) AS record_type, parameter.name AS parameter, observation.value AS value
FROM observation JOIN parameter ON observation.parameter_id = parameter.id
WHERE observation.record_type IN ('compositional analysis', 'proximate analysis', 'ultimate analysis', 'xrf analysis', 'icp analysis', 'calorimetry analysis', 'xrd analysis', 'ftnir analysis', 'pretreatment', 'gasification', 'fermentation')) AS anon_13 ON lower(anon_12.record_id) = lower(anon_13.record_id) AND anon_13.record_type = anon_12.type GROUP BY anon_12.resource_id) AS anon_3 ON anon_3.resource_id = resource.id LEFT OUTER JOIN (SELECT anon_3.resource_id AS resource_id, array_remove(ARRAY[CASE WHEN (anon_3.moisture_percent <= anon_24.moisture_low) THEN 'low moisture' END, CASE WHEN (anon_3.moisture_percent >= anon_24.moisture_high) THEN 'high moisture' END, CASE WHEN (anon_3.ash_percent <= anon_24.ash_low) THEN 'low ash' END, CASE WHEN (anon_3.ash_percent >= anon_24.ash_high) THEN 'high ash' END, CASE WHEN (anon_3.lignin_percent <= anon_24.lignin_low) THEN 'low lignin' END, CASE WHEN (anon_3.lignin_percent >= anon_24.lignin_high) THEN 'high lignin' END, CASE WHEN (anon_3.glucan_percent <= anon_24.glucan_low) THEN 'low glucan' END, CASE WHEN (anon_3.glucan_percent >= anon_24.glucan_high) THEN 'high glucan' END, CASE WHEN (anon_3.xylan_percent <= anon_24.xylan_low) THEN 'low xylan' END, CASE WHEN (anon_3.xylan_percent >= anon_24.xylan_high) THEN 'high xylan' END], NULL) AS tags
FROM (SELECT anon_12.resource_id AS resource_id, avg(CASE WHEN (anon_13.parameter = 'moisture') THEN anon_13.value END) AS moisture_percent, avg(CASE WHEN (anon_13.parameter = 'ash') THEN anon_13.value END) AS ash_percent, CASE WHEN (avg(CASE WHEN (anon_13.parameter = 'lignin') THEN anon_13.value END) IS NOT NULL OR avg(CASE WHEN (anon_13.parameter = 'lignin+') THEN anon_13.value END) IS NOT NULL) THEN coalesce(avg(CASE WHEN (anon_13.parameter = 'lignin') THEN anon_13.value END), 0) + coalesce(avg(CASE WHEN (anon_13.parameter = 'lignin+') THEN anon_13.value END), 0) END AS lignin_percent, CASE WHEN (avg(CASE WHEN (anon_13.parameter = 'glucose') THEN anon_13.value END) IS NOT NULL OR avg(CASE WHEN (anon_13.parameter = 'xylose') THEN anon_13.value END) IS NOT NULL) THEN coalesce(avg(CASE WHEN (anon_13.parameter = 'glucose') THEN anon_13.value END), 0) + coalesce(avg(CASE WHEN (anon_13.parameter = 'xylose') THEN anon_13.value END), 0) END AS sugar_content_percent, avg(CASE WHEN (anon_13.parameter = 'glucose') THEN anon_13.value END) AS glucan_percent, avg(CASE WHEN (anon_13.parameter = 'xylose') THEN anon_13.value END) AS xylan_percent, avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'carbon') THEN anon_13.value END) AS carbon_percent, avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'hydrogen') THEN anon_13.value END) AS hydrogen_percent, CASE WHEN (avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'carbon') THEN anon_13.value END) IS NOT NULL AND avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'nitrogen') THEN anon_13.value END) IS NOT NULL AND avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'nitrogen') THEN anon_13.value END) != 0) THEN avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'carbon') THEN anon_13.value END) / CAST(CAST(avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'nitrogen') THEN anon_13.value END) AS NUMERIC) AS NUMERIC) END AS cn_ratio, bool_or(anon_12.type = 'proximate analysis') AS has_proximate, bool_or(anon_12.type = 'compositional analysis') AS has_compositional, bool_or(anon_12.type = 'ultimate analysis') AS has_ultimate, bool_or(anon_12.type = 'xrf analysis') AS has_xrf, bool_or(anon_12.type = 'icp analysis') AS has_icp, bool_or(anon_12.type = 'calorimetry analysis') AS has_calorimetry, bool_or(anon_12.type = 'xrd analysis') AS has_xrd, bool_or(anon_12.type = 'ftnir analysis') AS has_ftnir, bool_or(anon_12.type = 'fermentation') AS has_fermentation, bool_or(anon_12.type = 'gasification') AS has_gasification, bool_or(anon_12.type = 'pretreatment') AS has_pretreatment
FROM (SELECT CAST(compositional_record.resource_id AS INTEGER) AS resource_id, CAST(compositional_record.record_id AS VARCHAR) AS record_id, 'compositional analysis' AS type
FROM compositional_record
WHERE compositional_record.qc_pass != 'fail' UNION ALL SELECT CAST(proximate_record.resource_id AS INTEGER) AS resource_id, CAST(proximate_record.record_id AS VARCHAR) AS record_id, 'proximate analysis' AS anon_14
FROM proximate_record
WHERE proximate_record.qc_pass != 'fail' UNION ALL SELECT CAST(ultimate_record.resource_id AS INTEGER) AS resource_id, CAST(ultimate_record.record_id AS VARCHAR) AS record_id, 'ultimate analysis' AS anon_15
FROM ultimate_record
WHERE ultimate_record.qc_pass != 'fail' UNION ALL SELECT CAST(xrf_record.resource_id AS INTEGER) AS resource_id, CAST(xrf_record.record_id AS VARCHAR) AS record_id, 'xrf analysis' AS anon_16
FROM xrf_record
WHERE xrf_record.qc_pass != 'fail' UNION ALL SELECT CAST(icp_record.resource_id AS INTEGER) AS resource_id, CAST(icp_record.record_id AS VARCHAR) AS record_id, 'icp analysis' AS anon_17
FROM icp_record
WHERE icp_record.qc_pass != 'fail' UNION ALL SELECT CAST(calorimetry_record.resource_id AS INTEGER) AS resource_id, CAST(calorimetry_record.record_id AS VARCHAR) AS record_id, 'calorimetry analysis' AS anon_18
FROM calorimetry_record
WHERE calorimetry_record.qc_pass != 'fail' UNION ALL SELECT CAST(xrd_record.resource_id AS INTEGER) AS resource_id, CAST(xrd_record.record_id AS VARCHAR) AS record_id, 'xrd analysis' AS anon_19
FROM xrd_record
WHERE xrd_record.qc_pass != 'fail' UNION ALL SELECT CAST(ftnir_record.resource_id AS INTEGER) AS resource_id, CAST(ftnir_record.record_id AS VARCHAR) AS record_id, 'ftnir analysis' AS anon_20
FROM ftnir_record
WHERE ftnir_record.qc_pass != 'fail' UNION ALL SELECT CAST(fermentation_record.resource_id AS INTEGER) AS resource_id, CAST(fermentation_record.record_id AS VARCHAR) AS record_id, 'fermentation' AS anon_21
FROM fermentation_record
WHERE fermentation_record.qc_pass != 'fail' UNION ALL SELECT CAST(gasification_record.resource_id AS INTEGER) AS resource_id, CAST(gasification_record.record_id AS VARCHAR) AS record_id, 'gasification' AS anon_22
FROM gasification_record
WHERE gasification_record.qc_pass != 'fail' UNION ALL SELECT CAST(pretreatment_record.resource_id AS INTEGER) AS resource_id, CAST(pretreatment_record.record_id AS VARCHAR) AS record_id, 'pretreatment' AS anon_23
FROM pretreatment_record
WHERE pretreatment_record.qc_pass != 'fail') AS anon_12 LEFT OUTER JOIN (SELECT CAST(observation.record_id AS VARCHAR) AS record_id, CAST(observation.record_type AS VARCHAR) AS record_type, parameter.name AS parameter, observation.value AS value
FROM observation JOIN parameter ON observation.parameter_id = parameter.id
WHERE observation.record_type IN ('compositional analysis', 'proximate analysis', 'ultimate analysis', 'xrf analysis', 'icp analysis', 'calorimetry analysis', 'xrd analysis', 'ftnir analysis', 'pretreatment', 'gasification', 'fermentation')) AS anon_13 ON lower(anon_12.record_id) = lower(anon_13.record_id) AND anon_13.record_type = anon_12.type GROUP BY anon_12.resource_id) AS anon_3 JOIN (SELECT percentile_cont(0.1) WITHIN GROUP (ORDER BY anon_3.moisture_percent) AS moisture_low, percentile_cont(0.9) WITHIN GROUP (ORDER BY anon_3.moisture_percent) AS moisture_high, percentile_cont(0.1) WITHIN GROUP (ORDER BY anon_3.ash_percent) AS ash_low, percentile_cont(0.9) WITHIN GROUP (ORDER BY anon_3.ash_percent) AS ash_high, percentile_cont(0.1) WITHIN GROUP (ORDER BY anon_3.lignin_percent) AS lignin_low, percentile_cont(0.9) WITHIN GROUP (ORDER BY anon_3.lignin_percent) AS lignin_high, percentile_cont(0.1) WITHIN GROUP (ORDER BY anon_3.sugar_content_percent) AS sugar_low, percentile_cont(0.9) WITHIN GROUP (ORDER BY anon_3.sugar_content_percent) AS sugar_high, percentile_cont(0.1) WITHIN GROUP (ORDER BY anon_3.glucan_percent) AS glucan_low, percentile_cont(0.9) WITHIN GROUP (ORDER BY anon_3.glucan_percent) AS glucan_high, percentile_cont(0.1) WITHIN GROUP (ORDER BY anon_3.xylan_percent) AS xylan_low, percentile_cont(0.9) WITHIN GROUP (ORDER BY anon_3.xylan_percent) AS xylan_high
FROM (SELECT anon_12.resource_id AS resource_id, avg(CASE WHEN (anon_13.parameter = 'moisture') THEN anon_13.value END) AS moisture_percent, avg(CASE WHEN (anon_13.parameter = 'ash') THEN anon_13.value END) AS ash_percent, CASE WHEN (avg(CASE WHEN (anon_13.parameter = 'lignin') THEN anon_13.value END) IS NOT NULL OR avg(CASE WHEN (anon_13.parameter = 'lignin+') THEN anon_13.value END) IS NOT NULL) THEN coalesce(avg(CASE WHEN (anon_13.parameter = 'lignin') THEN anon_13.value END), 0) + coalesce(avg(CASE WHEN (anon_13.parameter = 'lignin+') THEN anon_13.value END), 0) END AS lignin_percent, CASE WHEN (avg(CASE WHEN (anon_13.parameter = 'glucose') THEN anon_13.value END) IS NOT NULL OR avg(CASE WHEN (anon_13.parameter = 'xylose') THEN anon_13.value END) IS NOT NULL) THEN coalesce(avg(CASE WHEN (anon_13.parameter = 'glucose') THEN anon_13.value END), 0) + coalesce(avg(CASE WHEN (anon_13.parameter = 'xylose') THEN anon_13.value END), 0) END AS sugar_content_percent, avg(CASE WHEN (anon_13.parameter = 'glucose') THEN anon_13.value END) AS glucan_percent, avg(CASE WHEN (anon_13.parameter = 'xylose') THEN anon_13.value END) AS xylan_percent, avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'carbon') THEN anon_13.value END) AS carbon_percent, avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'hydrogen') THEN anon_13.value END) AS hydrogen_percent, CASE WHEN (avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'carbon') THEN anon_13.value END) IS NOT NULL AND avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'nitrogen') THEN anon_13.value END) IS NOT NULL AND avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'nitrogen') THEN anon_13.value END) != 0) THEN avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'carbon') THEN anon_13.value END) / CAST(CAST(avg(CASE WHEN (anon_12.type = 'ultimate analysis' AND lower(anon_13.parameter) = 'nitrogen') THEN anon_13.value END) AS NUMERIC) AS NUMERIC) END AS cn_ratio, bool_or(anon_12.type = 'proximate analysis') AS has_proximate, bool_or(anon_12.type = 'compositional analysis') AS has_compositional, bool_or(anon_12.type = 'ultimate analysis') AS has_ultimate, bool_or(anon_12.type = 'xrf analysis') AS has_xrf, bool_or(anon_12.type = 'icp analysis') AS has_icp, bool_or(anon_12.type = 'calorimetry analysis') AS has_calorimetry, bool_or(anon_12.type = 'xrd analysis') AS has_xrd, bool_or(anon_12.type = 'ftnir analysis') AS has_ftnir, bool_or(anon_12.type = 'fermentation') AS has_fermentation, bool_or(anon_12.type = 'gasification') AS has_gasification, bool_or(anon_12.type = 'pretreatment') AS has_pretreatment
FROM (SELECT CAST(compositional_record.resource_id AS INTEGER) AS resource_id, CAST(compositional_record.record_id AS VARCHAR) AS record_id, 'compositional analysis' AS type
FROM compositional_record
WHERE compositional_record.qc_pass != 'fail' UNION ALL SELECT CAST(proximate_record.resource_id AS INTEGER) AS resource_id, CAST(proximate_record.record_id AS VARCHAR) AS record_id, 'proximate analysis' AS anon_14
FROM proximate_record
WHERE proximate_record.qc_pass != 'fail' UNION ALL SELECT CAST(ultimate_record.resource_id AS INTEGER) AS resource_id, CAST(ultimate_record.record_id AS VARCHAR) AS record_id, 'ultimate analysis' AS anon_15
FROM ultimate_record
WHERE ultimate_record.qc_pass != 'fail' UNION ALL SELECT CAST(xrf_record.resource_id AS INTEGER) AS resource_id, CAST(xrf_record.record_id AS VARCHAR) AS record_id, 'xrf analysis' AS anon_16
FROM xrf_record
WHERE xrf_record.qc_pass != 'fail' UNION ALL SELECT CAST(icp_record.resource_id AS INTEGER) AS resource_id, CAST(icp_record.record_id AS VARCHAR) AS record_id, 'icp analysis' AS anon_17
FROM icp_record
WHERE icp_record.qc_pass != 'fail' UNION ALL SELECT CAST(calorimetry_record.resource_id AS INTEGER) AS resource_id, CAST(calorimetry_record.record_id AS VARCHAR) AS record_id, 'calorimetry analysis' AS anon_18
FROM calorimetry_record
WHERE calorimetry_record.qc_pass != 'fail' UNION ALL SELECT CAST(xrd_record.resource_id AS INTEGER) AS resource_id, CAST(xrd_record.record_id AS VARCHAR) AS record_id, 'xrd analysis' AS anon_19
FROM xrd_record
WHERE xrd_record.qc_pass != 'fail' UNION ALL SELECT CAST(ftnir_record.resource_id AS INTEGER) AS resource_id, CAST(ftnir_record.record_id AS VARCHAR) AS record_id, 'ftnir analysis' AS anon_20
FROM ftnir_record
WHERE ftnir_record.qc_pass != 'fail' UNION ALL SELECT CAST(fermentation_record.resource_id AS INTEGER) AS resource_id, CAST(fermentation_record.record_id AS VARCHAR) AS record_id, 'fermentation' AS anon_21
FROM fermentation_record
WHERE fermentation_record.qc_pass != 'fail' UNION ALL SELECT CAST(gasification_record.resource_id AS INTEGER) AS resource_id, CAST(gasification_record.record_id AS VARCHAR) AS record_id, 'gasification' AS anon_22
FROM gasification_record
WHERE gasification_record.qc_pass != 'fail' UNION ALL SELECT CAST(pretreatment_record.resource_id AS INTEGER) AS resource_id, CAST(pretreatment_record.record_id AS VARCHAR) AS record_id, 'pretreatment' AS anon_23
FROM pretreatment_record
WHERE pretreatment_record.qc_pass != 'fail') AS anon_12 LEFT OUTER JOIN (SELECT CAST(observation.record_id AS VARCHAR) AS record_id, CAST(observation.record_type AS VARCHAR) AS record_type, parameter.name AS parameter, observation.value AS value
FROM observation JOIN parameter ON observation.parameter_id = parameter.id
WHERE observation.record_type IN ('compositional analysis', 'proximate analysis', 'ultimate analysis', 'xrf analysis', 'icp analysis', 'calorimetry analysis', 'xrd analysis', 'ftnir analysis', 'pretreatment', 'gasification', 'fermentation')) AS anon_13 ON lower(anon_12.record_id) = lower(anon_13.record_id) AND anon_13.record_type = anon_12.type GROUP BY anon_12.resource_id) AS anon_3) AS anon_24 ON true) AS anon_6 ON anon_6.resource_id = resource.id LEFT OUTER JOIN (SELECT resource.id AS resource_id, resource.name AS resource_name, min(resource_availability.from_month) AS from_month, max(resource_availability.to_month) AS to_month, bool_or(resource_availability.year_round) AS year_round, avg(resource_availability.residue_factor_dry_tons_acre) AS dry_tons_per_acre, avg(resource_availability.residue_factor_wet_tons_acre) AS wet_tons_per_acre
FROM resource_availability JOIN resource ON resource_availability.resource_id = resource.id GROUP BY resource.id, resource.name) AS anon_7 ON anon_7.resource_id = resource.id LEFT OUTER JOIN (SELECT resource_transport_record.resource_id AS resource_id, max(resource_transport_record.transport_description) AS transport_notes
FROM resource_transport_record GROUP BY resource_transport_record.resource_id) AS anon_4 ON anon_4.resource_id = resource.id LEFT OUTER JOIN (SELECT resource_storage_record.resource_id AS resource_id, max(resource_storage_record.storage_description) AS storage_notes
FROM resource_storage_record GROUP BY resource_storage_record.resource_id) AS anon_5 ON anon_5.resource_id = resource.id
WHERE lower(resource.name) != 'sargassum' AND lower(resource.name) != 'lab media'
    """)
    # data_portal.mv_biomass_composition
    op.execute("""
        CREATE MATERIALIZED VIEW data_portal.mv_biomass_composition AS
        SELECT row_number() OVER (ORDER BY anon_1.resource_id, anon_1.geoid, anon_1.analysis_type, anon_1.parameter_name, anon_1.unit) AS id, anon_1.resource_id, resource.name AS resource_name, anon_1.analysis_type, anon_1.parameter_name, anon_1.geoid, place.county_name AS county, anon_1.unit, avg(anon_1.value) AS avg_value, min(anon_1.value) AS min_value, max(anon_1.value) AS max_value, stddev(anon_1.value) AS std_dev, count(*) AS observation_count
FROM (SELECT compositional_record.resource_id AS resource_id, 'compositional' AS analysis_type, parameter.name AS parameter_name, observation.value AS value, unit.name AS unit, location_address.geography_id AS geoid
FROM compositional_record JOIN observation ON observation.record_id = compositional_record.record_id JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN prepared_sample ON compositional_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
WHERE compositional_record.qc_pass != 'fail' UNION ALL SELECT proximate_record.resource_id AS resource_id, 'proximate' AS analysis_type, parameter.name AS parameter_name, observation.value AS value, unit.name AS unit, location_address.geography_id AS geoid
FROM proximate_record JOIN observation ON observation.record_id = proximate_record.record_id JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN prepared_sample ON proximate_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
WHERE proximate_record.qc_pass != 'fail' UNION ALL SELECT ultimate_record.resource_id AS resource_id, 'ultimate' AS analysis_type, parameter.name AS parameter_name, observation.value AS value, unit.name AS unit, location_address.geography_id AS geoid
FROM ultimate_record JOIN observation ON observation.record_id = ultimate_record.record_id JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN prepared_sample ON ultimate_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
WHERE ultimate_record.qc_pass != 'fail' UNION ALL SELECT xrf_record.resource_id AS resource_id, 'xrf' AS analysis_type, parameter.name AS parameter_name, observation.value AS value, unit.name AS unit, location_address.geography_id AS geoid
FROM xrf_record JOIN observation ON observation.record_id = xrf_record.record_id JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN prepared_sample ON xrf_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
WHERE xrf_record.qc_pass != 'fail' UNION ALL SELECT icp_record.resource_id AS resource_id, 'icp' AS analysis_type, parameter.name AS parameter_name, observation.value AS value, unit.name AS unit, location_address.geography_id AS geoid
FROM icp_record JOIN observation ON observation.record_id = icp_record.record_id JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN prepared_sample ON icp_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
WHERE icp_record.qc_pass != 'fail' UNION ALL SELECT calorimetry_record.resource_id AS resource_id, 'calorimetry' AS analysis_type, parameter.name AS parameter_name, observation.value AS value, unit.name AS unit, location_address.geography_id AS geoid
FROM calorimetry_record JOIN observation ON observation.record_id = calorimetry_record.record_id JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN prepared_sample ON calorimetry_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
WHERE calorimetry_record.qc_pass != 'fail' UNION ALL SELECT xrd_record.resource_id AS resource_id, 'xrd' AS analysis_type, parameter.name AS parameter_name, observation.value AS value, unit.name AS unit, location_address.geography_id AS geoid
FROM xrd_record JOIN observation ON observation.record_id = xrd_record.record_id JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN prepared_sample ON xrd_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
WHERE xrd_record.qc_pass != 'fail' UNION ALL SELECT ftnir_record.resource_id AS resource_id, 'ftnir' AS analysis_type, parameter.name AS parameter_name, observation.value AS value, unit.name AS unit, location_address.geography_id AS geoid
FROM ftnir_record JOIN observation ON observation.record_id = ftnir_record.record_id JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN prepared_sample ON ftnir_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
WHERE ftnir_record.qc_pass != 'fail' UNION ALL SELECT pretreatment_record.resource_id AS resource_id, 'pretreatment' AS analysis_type, parameter.name AS parameter_name, observation.value AS value, unit.name AS unit, location_address.geography_id AS geoid
FROM pretreatment_record JOIN observation ON observation.record_id = pretreatment_record.record_id JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id LEFT OUTER JOIN prepared_sample ON pretreatment_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id
WHERE pretreatment_record.qc_pass != 'fail') AS anon_1 JOIN resource ON anon_1.resource_id = resource.id LEFT OUTER JOIN place ON anon_1.geoid = place.geoid GROUP BY anon_1.resource_id, resource.name, anon_1.analysis_type, anon_1.parameter_name, anon_1.geoid, place.county_name, anon_1.unit
    """)
    # data_portal.mv_biomass_county_production
    op.execute("""
        CREATE MATERIALIZED VIEW data_portal.mv_biomass_county_production AS
        SELECT row_number() OVER (ORDER BY billion_ton2023_record.resource_id, place.geoid, billion_ton2023_record.scenario_name, billion_ton2023_record.price_offered_usd) AS id, billion_ton2023_record.resource_id, resource.name AS resource_name, resource_class.name AS resource_class, place.geoid, place.county_name AS county, place.state_name AS state, billion_ton2023_record.scenario_name AS scenario, billion_ton2023_record.price_offered_usd, billion_ton2023_record.production, unit.name AS production_unit, billion_ton2023_record.production_energy_content AS energy_content, eu.name AS energy_unit, billion_ton2023_record.product_density_dtpersqmi AS density_dt_per_sqmi, billion_ton2023_record.county_square_miles, 2023 AS year
FROM billion_ton2023_record JOIN resource ON billion_ton2023_record.resource_id = resource.id LEFT OUTER JOIN resource_class ON resource.resource_class_id = resource_class.id JOIN place ON billion_ton2023_record.geoid = place.geoid LEFT OUTER JOIN unit ON billion_ton2023_record.production_unit_id = unit.id LEFT OUTER JOIN unit AS eu ON billion_ton2023_record.energy_content_unit_id = eu.id
    """)
    # data_portal.mv_biomass_sample_stats
    op.execute("""
        CREATE MATERIALIZED VIEW data_portal.mv_biomass_sample_stats AS
        SELECT resource.id AS resource_id, resource.name AS resource_name, count(distinct(anon_1.prepared_sample_id)) AS sample_count, count(distinct(provider.id)) AS supplier_count, count(distinct(anon_1.dataset_id)) AS dataset_count, count(*) AS total_record_count
FROM resource LEFT OUTER JOIN (SELECT compositional_record.resource_id AS resource_id, compositional_record.prepared_sample_id AS prepared_sample_id, compositional_record.dataset_id AS dataset_id
FROM compositional_record
WHERE compositional_record.qc_pass != 'fail' UNION ALL SELECT proximate_record.resource_id AS resource_id, proximate_record.prepared_sample_id AS prepared_sample_id, proximate_record.dataset_id AS dataset_id
FROM proximate_record
WHERE proximate_record.qc_pass != 'fail' UNION ALL SELECT ultimate_record.resource_id AS resource_id, ultimate_record.prepared_sample_id AS prepared_sample_id, ultimate_record.dataset_id AS dataset_id
FROM ultimate_record
WHERE ultimate_record.qc_pass != 'fail' UNION ALL SELECT xrf_record.resource_id AS resource_id, xrf_record.prepared_sample_id AS prepared_sample_id, xrf_record.dataset_id AS dataset_id
FROM xrf_record
WHERE xrf_record.qc_pass != 'fail' UNION ALL SELECT icp_record.resource_id AS resource_id, icp_record.prepared_sample_id AS prepared_sample_id, icp_record.dataset_id AS dataset_id
FROM icp_record
WHERE icp_record.qc_pass != 'fail' UNION ALL SELECT calorimetry_record.resource_id AS resource_id, calorimetry_record.prepared_sample_id AS prepared_sample_id, calorimetry_record.dataset_id AS dataset_id
FROM calorimetry_record
WHERE calorimetry_record.qc_pass != 'fail' UNION ALL SELECT xrd_record.resource_id AS resource_id, xrd_record.prepared_sample_id AS prepared_sample_id, xrd_record.dataset_id AS dataset_id
FROM xrd_record
WHERE xrd_record.qc_pass != 'fail' UNION ALL SELECT ftnir_record.resource_id AS resource_id, ftnir_record.prepared_sample_id AS prepared_sample_id, ftnir_record.dataset_id AS dataset_id
FROM ftnir_record
WHERE ftnir_record.qc_pass != 'fail' UNION ALL SELECT fermentation_record.resource_id AS resource_id, fermentation_record.prepared_sample_id AS prepared_sample_id, fermentation_record.dataset_id AS dataset_id
FROM fermentation_record
WHERE fermentation_record.qc_pass != 'fail' UNION ALL SELECT gasification_record.resource_id AS resource_id, gasification_record.prepared_sample_id AS prepared_sample_id, gasification_record.dataset_id AS dataset_id
FROM gasification_record
WHERE gasification_record.qc_pass != 'fail' UNION ALL SELECT pretreatment_record.resource_id AS resource_id, pretreatment_record.prepared_sample_id AS prepared_sample_id, pretreatment_record.dataset_id AS dataset_id
FROM pretreatment_record
WHERE pretreatment_record.qc_pass != 'fail') AS anon_1 ON anon_1.resource_id = resource.id LEFT OUTER JOIN prepared_sample ON CAST(anon_1.prepared_sample_id AS INTEGER) = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN provider ON field_sample.provider_id = provider.id GROUP BY resource.id, resource.name
    """)
    # data_portal.mv_biomass_fermentation
    op.execute("""
        CREATE MATERIALIZED VIEW data_portal.mv_biomass_fermentation AS
        SELECT row_number() OVER (ORDER BY fermentation_record.resource_id, location_address.geography_id, strain.name, pm.name, em.name, bcm.name, parameter.name, unit.name) AS id, fermentation_record.resource_id, resource.name AS resource_name, location_address.geography_id AS geoid, place.county_name AS county, concat(upper(left(strain.genus, 1)), '. ', lower(strain.species)) AS strain_name, pm.name AS pretreatment_method, em.name AS enzyme_name, bcm.name AS bioconversion_method, coalesce(pm.duration, em.duration, bcm.time_h) AS elapsed_time, parameter.name AS product_name, avg(observation.value) AS avg_value, min(observation.value) AS min_value, max(observation.value) AS max_value, stddev(observation.value) AS std_dev, count(*) AS observation_count, unit.name AS unit
FROM fermentation_record JOIN resource ON fermentation_record.resource_id = resource.id LEFT OUTER JOIN prepared_sample ON fermentation_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id LEFT OUTER JOIN place ON location_address.geography_id = place.geoid LEFT OUTER JOIN strain ON fermentation_record.strain_id = strain.id LEFT OUTER JOIN method AS pm ON fermentation_record.pretreatment_method_id = pm.id LEFT OUTER JOIN method AS em ON fermentation_record.eh_method_id = em.id LEFT OUTER JOIN bioconversion_method AS bcm ON fermentation_record.bioconversion_method_id = bcm.id JOIN observation ON lower(observation.record_id) = lower(fermentation_record.record_id) JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id
WHERE fermentation_record.qc_pass != 'fail' GROUP BY fermentation_record.resource_id, resource.name, location_address.geography_id, place.county_name, strain.name, strain.genus, strain.species, pm.name, em.name, bcm.name, coalesce(pm.duration, em.duration, bcm.time_h), parameter.name, unit.name
    """)
    # data_portal.mv_biomass_gasification
    op.execute("""
        CREATE MATERIALIZED VIEW data_portal.mv_biomass_gasification AS
        SELECT row_number() OVER (ORDER BY gasification_record.resource_id, location_address.geography_id, decon_vessel.name, parameter.name, unit.name) AS id, gasification_record.resource_id, resource.name AS resource_name, decon_vessel.name AS reactor_type, parameter.name AS parameter_name, location_address.geography_id AS geoid, avg(observation.value) AS avg_value, min(observation.value) AS min_value, max(observation.value) AS max_value, stddev(observation.value) AS std_dev, count(*) AS observation_count, unit.name AS unit
FROM gasification_record JOIN resource ON gasification_record.resource_id = resource.id LEFT OUTER JOIN prepared_sample ON gasification_record.prepared_sample_id = prepared_sample.id LEFT OUTER JOIN field_sample ON prepared_sample.field_sample_id = field_sample.id LEFT OUTER JOIN location_address ON field_sample.sampling_location_id = location_address.id LEFT OUTER JOIN decon_vessel ON gasification_record.reactor_type_id = decon_vessel.id JOIN observation ON lower(observation.record_id) = lower(gasification_record.record_id) JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id
WHERE gasification_record.qc_pass != 'fail' GROUP BY gasification_record.resource_id, resource.name, location_address.geography_id, decon_vessel.name, parameter.name, unit.name
    """)
    # data_portal.mv_biomass_pricing
    op.execute("""
        CREATE MATERIALIZED VIEW data_portal.mv_biomass_pricing AS
        SELECT row_number() OVER (ORDER BY usda_market_record.id) AS id, usda_commodity.name AS commodity_name, place.geoid, place.county_name AS county, place.state_name AS state, usda_market_record.report_date, usda_market_record.market_type_category, usda_market_record.sale_type, anon_1.price_min, anon_1.price_max, anon_1.price_avg, anon_1.price_unit
FROM usda_market_record JOIN usda_market_report ON usda_market_record.report_id = usda_market_report.id JOIN usda_commodity ON usda_market_record.commodity_id = usda_commodity.id LEFT OUTER JOIN location_address ON usda_market_report.office_city_id = location_address.id LEFT OUTER JOIN place ON location_address.geography_id = place.geoid JOIN (SELECT observation.record_id AS record_id, avg(observation.value) AS price_avg, min(observation.value) AS price_min, max(observation.value) AS price_max, unit.name AS price_unit
FROM observation JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id
WHERE observation.record_type = 'usda_market_record' AND lower(parameter.name) = 'price received' GROUP BY observation.record_id, unit.name) AS anon_1 ON CAST(usda_market_record.id AS VARCHAR) = anon_1.record_id
    """)
    # data_portal.mv_usda_county_production
    op.execute("""
        CREATE MATERIALIZED VIEW data_portal.mv_usda_county_production AS
        SELECT row_number() OVER (ORDER BY resource.id, place.geoid, usda_census_record.year) AS id, resource.id AS resource_id, resource.name AS resource_name, primary_ag_product.name AS primary_ag_product, place.geoid, place.county_name AS county, place.state_name AS state, usda_census_record.year AS dataset_year, avg(anon_1.primary_product_volume) AS primary_product_volume, max(anon_1.volume_unit) AS volume_unit, avg(anon_1.production_acres) AS production_acres, NULL AS known_biomass_volume, avg(anon_1.production_acres) * coalesce(max(CASE WHEN (anon_2.geoid = place.geoid) THEN anon_2.residue_factor_dry_tons_acre END), max(CASE WHEN (anon_2.geoid = '06000') THEN anon_2.residue_factor_dry_tons_acre END)) AS calculated_estimate_volume, 'dry_tons_acre' AS biomass_unit
FROM usda_census_record JOIN resource_usda_commodity_map ON usda_census_record.commodity_code = resource_usda_commodity_map.usda_commodity_id JOIN resource ON resource_usda_commodity_map.resource_id = resource.id JOIN primary_ag_product ON resource.primary_ag_product_id = primary_ag_product.id JOIN place ON usda_census_record.geoid = place.geoid JOIN (SELECT observation.record_id AS record_id, avg(CASE WHEN (lower(parameter.name) = 'production') THEN observation.value END) AS primary_product_volume, max(CASE WHEN (lower(parameter.name) = 'production') THEN unit.name END) AS volume_unit, avg(CASE WHEN (lower(parameter.name) IN ('area bearing', 'area harvested', 'area in production') AND lower(unit.name) = 'acres') THEN observation.value END) AS production_acres
FROM observation JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id
WHERE observation.record_type = 'usda_census_record' GROUP BY observation.record_id) AS anon_1 ON CAST(usda_census_record.id AS VARCHAR) = anon_1.record_id LEFT OUTER JOIN (SELECT resource_availability.resource_id AS resource_id, resource_availability.geoid AS geoid, resource_availability.residue_factor_dry_tons_acre AS residue_factor_dry_tons_acre
FROM resource_availability) AS anon_2 ON resource.id = anon_2.resource_id
WHERE usda_census_record.year >= 2017 GROUP BY resource.id, resource.name, primary_ag_product.name, place.geoid, place.county_name, place.state_name, usda_census_record.year
    """)
    # data_portal.mv_biomass_end_uses
    op.execute("""
        CREATE MATERIALIZED VIEW data_portal.mv_biomass_end_uses AS
        SELECT resource_end_use_record.resource_id, resource.name AS resource_name, coalesce(use_case.name, 'unknown') AS use_case, CAST(avg(anon_1.percentage_low) AS FLOAT) AS percentage_low, CAST(avg(anon_1.percentage_high) AS FLOAT) AS percentage_high, CAST(max(anon_1.trend) AS TEXT) AS trend, CAST(avg(anon_1.value_low_usd) AS FLOAT) AS value_low_usd, CAST(avg(anon_1.value_high_usd) AS FLOAT) AS value_high_usd, CAST(max(anon_1.value_unit) AS TEXT) AS value_notes
FROM resource_end_use_record JOIN resource ON resource_end_use_record.resource_id = resource.id LEFT OUTER JOIN use_case ON resource_end_use_record.use_case_id = use_case.id LEFT OUTER JOIN (SELECT observation.record_id AS record_id, avg(CASE WHEN (lower(parameter.name) = 'resource_use_perc_low') THEN observation.value END) AS percentage_low, avg(CASE WHEN (lower(parameter.name) = 'resource_use_perc_high') THEN observation.value END) AS percentage_high, avg(CASE WHEN (lower(parameter.name) = 'resource_value_low') THEN observation.value END) AS value_low_usd, avg(CASE WHEN (lower(parameter.name) = 'resource_value_high') THEN observation.value END) AS value_high_usd, max(CASE WHEN (lower(parameter.name) = 'resource_use_perc_low') THEN unit.name END) AS unit, max(CASE WHEN (lower(parameter.name) = 'resource_use_trend') THEN CAST(observation.note AS VARCHAR) END) AS trend, max(CASE WHEN (lower(parameter.name) IN ('resource_value_low', 'resource_value_high')) THEN unit.name END) AS value_unit
FROM observation JOIN parameter ON observation.parameter_id = parameter.id LEFT OUTER JOIN unit ON observation.unit_id = unit.id
WHERE lower(observation.record_type) = 'resource_end_use_record' GROUP BY observation.record_id) AS anon_1 ON CAST(resource_end_use_record.id AS VARCHAR) = anon_1.record_id
WHERE resource_end_use_record.resource_id IS NOT NULL GROUP BY resource_end_use_record.resource_id, resource.name, coalesce(use_case.name, 'unknown')
    """)
    # --- Indexes ---
    # ca_biositing
    op.execute("""CREATE INDEX idx_landiq_record_view_geom ON ca_biositing.landiq_record_view USING GIST (geom)""")
    op.execute("""CREATE INDEX idx_landiq_tileset_view_geom ON ca_biositing.landiq_tileset_view USING GIST (geom)""")
    op.execute("""CREATE UNIQUE INDEX idx_mv_biomass_volume_estimate_id ON data_portal.mv_biomass_volume_estimate (id)""")
    op.execute("""CREATE UNIQUE INDEX idx_mv_biomass_search_id ON data_portal.mv_biomass_search (id)""")
    op.execute("""CREATE INDEX idx_mv_biomass_search_search_vector ON data_portal.mv_biomass_search USING GIN (search_vector)""")
    op.execute("""CREATE INDEX idx_mv_biomass_search_name_trgm ON data_portal.mv_biomass_search USING GIN (name gin_trgm_ops)""")
    op.execute("""CREATE INDEX idx_mv_biomass_search_resource_class ON data_portal.mv_biomass_search (resource_class)""")
    op.execute("""CREATE INDEX idx_mv_biomass_search_resource_subclass ON data_portal.mv_biomass_search (resource_subclass)""")
    op.execute("""CREATE INDEX idx_mv_biomass_search_primary_product ON data_portal.mv_biomass_search (primary_product)""")
    op.execute("""CREATE UNIQUE INDEX idx_mv_biomass_composition_id ON data_portal.mv_biomass_composition (id)""")
    op.execute("""CREATE INDEX idx_mv_biomass_composition_resource_id ON data_portal.mv_biomass_composition (resource_id)""")
    op.execute("""CREATE INDEX idx_mv_biomass_composition_geoid ON data_portal.mv_biomass_composition (geoid)""")
    op.execute("""CREATE INDEX idx_mv_biomass_composition_county ON data_portal.mv_biomass_composition (county)""")
    op.execute("""CREATE INDEX idx_mv_biomass_composition_analysis_type ON data_portal.mv_biomass_composition (analysis_type)""")
    op.execute("""CREATE INDEX idx_mv_biomass_composition_parameter_name ON data_portal.mv_biomass_composition (parameter_name)""")
    op.execute("""CREATE INDEX idx_mv_biomass_composition_resource_analysis ON data_portal.mv_biomass_composition (resource_id, analysis_type)""")
    op.execute("""CREATE INDEX idx_mv_biomass_composition_resource_geoid_analysis ON data_portal.mv_biomass_composition (resource_id, geoid, analysis_type)""")
    op.execute("""CREATE UNIQUE INDEX idx_mv_usda_county_production_id ON data_portal.mv_usda_county_production (id)""")
    op.execute("""CREATE INDEX idx_mv_usda_county_production_resource_id ON data_portal.mv_usda_county_production (resource_id)""")
    op.execute("""CREATE INDEX idx_mv_usda_county_production_geoid ON data_portal.mv_usda_county_production (geoid)""")
    op.execute("""CREATE UNIQUE INDEX idx_mv_biomass_availability_resource_id ON data_portal.mv_biomass_availability (resource_id)""")
    op.execute("""CREATE UNIQUE INDEX idx_mv_biomass_sample_stats_resource_id ON data_portal.mv_biomass_sample_stats (resource_id)""")
    op.execute("""CREATE UNIQUE INDEX idx_mv_biomass_fermentation_id ON data_portal.mv_biomass_fermentation (id)""")
    op.execute("""CREATE INDEX idx_mv_biomass_fermentation_resource_id ON data_portal.mv_biomass_fermentation (resource_id)""")
    op.execute("""CREATE INDEX idx_mv_biomass_fermentation_geoid ON data_portal.mv_biomass_fermentation (geoid)""")
    op.execute("""CREATE INDEX idx_mv_biomass_fermentation_county ON data_portal.mv_biomass_fermentation (county)""")
    op.execute("""CREATE INDEX idx_mv_biomass_fermentation_strain_name ON data_portal.mv_biomass_fermentation (strain_name)""")
    op.execute("""CREATE INDEX idx_mv_biomass_fermentation_product_name ON data_portal.mv_biomass_fermentation (product_name)""")
    op.execute("""CREATE INDEX idx_mv_biomass_fermentation_resource_strain ON data_portal.mv_biomass_fermentation (resource_id, strain_name)""")
    op.execute("""CREATE UNIQUE INDEX idx_mv_biomass_gasification_id ON data_portal.mv_biomass_gasification (id)""")
    op.execute("""CREATE INDEX idx_mv_biomass_gasification_resource_id ON data_portal.mv_biomass_gasification (resource_id)""")
    op.execute("""CREATE INDEX idx_mv_biomass_gasification_reactor_type ON data_portal.mv_biomass_gasification (reactor_type)""")
    op.execute("""CREATE INDEX idx_mv_biomass_gasification_parameter_name ON data_portal.mv_biomass_gasification (parameter_name)""")
    op.execute("""CREATE INDEX idx_mv_biomass_gasification_resource_reactor_param ON data_portal.mv_biomass_gasification (resource_id, reactor_type, parameter_name)""")
    op.execute("""CREATE UNIQUE INDEX idx_mv_biomass_pricing_id ON data_portal.mv_biomass_pricing (id)""")
    op.execute("""CREATE INDEX idx_mv_biomass_pricing_commodity_name ON data_portal.mv_biomass_pricing (commodity_name)""")
    op.execute("""CREATE INDEX idx_mv_biomass_pricing_county ON data_portal.mv_biomass_pricing (county)""")
    op.execute("""CREATE UNIQUE INDEX idx_mv_biomass_end_uses_resource_use_case ON data_portal.mv_biomass_end_uses (resource_id, use_case)""")
    op.execute("""CREATE INDEX idx_mv_biomass_end_uses_resource_id ON data_portal.mv_biomass_end_uses (resource_id)""")
    op.execute("""CREATE UNIQUE INDEX idx_mv_biomass_county_production_id ON data_portal.mv_biomass_county_production (id)""")
    # --- Permissions ---
    op.execute("""GRANT USAGE ON SCHEMA data_portal TO biocirv_readonly""")
    op.execute("""GRANT SELECT ON ALL TABLES IN SCHEMA data_portal TO biocirv_readonly""")
    op.execute("""GRANT USAGE ON SCHEMA ca_biositing TO biocirv_readonly""")
    op.execute("""GRANT SELECT ON ALL TABLES IN SCHEMA ca_biositing TO biocirv_readonly""")

def downgrade() -> None:
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_end_uses CASCADE""")
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_usda_county_production CASCADE""")
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_pricing CASCADE""")
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_gasification CASCADE""")
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_fermentation CASCADE""")
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_sample_stats CASCADE""")
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_county_production CASCADE""")
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_composition CASCADE""")
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_search CASCADE""")
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_volume_estimate CASCADE""")
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS data_portal.mv_biomass_availability CASCADE""")
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS ca_biositing.analysis_average_view CASCADE""")
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS ca_biositing.billion_ton_tileset_view CASCADE""")
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS ca_biositing.usda_resource_commodity_view CASCADE""")
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS ca_biositing.usda_survey_view CASCADE""")
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS ca_biositing.usda_census_view CASCADE""")
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS ca_biositing.analysis_data_view CASCADE""")
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS ca_biositing.landiq_tileset_view CASCADE""")
    op.execute("""DROP MATERIALIZED VIEW IF EXISTS ca_biositing.landiq_record_view CASCADE""")
