"""updated biodiesel plants and added petroleum pipelines

Revision ID: add_petroleum_pipelines
Revises: consolidated_views_volume
Create Date: 2026-04-09 09:35:52.160720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'add_petroleum_pipelines'
down_revision: Union[str, Sequence[str], None] = 'consolidated_views_volume'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infrastructure_biodiesel_plants', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_biodiesel_plants', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('infrastructure_biodiesel_plants', 'address',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='address::integer')
    op.create_table('infrastructure_petroleum_pipelines',
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('operator_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pipeline_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pipeline_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('artificial', sa.Integer(), nullable=True),
    sa.Column('master_oid', sa.Integer(), nullable=True),
    sa.Column('commodity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.Column('capacity', sa.Numeric(), nullable=True),
    sa.Column('vcr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('shape_length', sa.Numeric(), nullable=True),
    sa.Column('mode_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('length', sa.Numeric(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry("MULTILINESTRING"), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Integer(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('object_id'),
    )
    op.create_table('multilinestring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Integer(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.Column('geoid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(spatial_index=False), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['dataset.id'], ),
    sa.ForeignKeyConstraint(['etl_run_id'], ['etl_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('infrastructure_petroleum_pipelines')
    op.drop_table('multilinestring')
    op.alter_column('infrastructure_biodiesel_plants', 'address',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('infrastructure_biodiesel_plants', 'updated_at')
    op.drop_column('infrastructure_biodiesel_plants', 'created_at')
    # ### end Alembic commands ###
