"""Add pretreatment_setup and enz_hydr_method tables

Revision ID: 0011
Revises: 0010
Create Date: 2026-05-19 10:59:36.457255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: Union[str, Sequence[str], None] = '0010'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enz_hydr_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Integer(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.Column('eh_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('eh_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enzyme_formulation', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reaction_volume_ul', sa.Float(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('time_h', sa.Float(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('protocol_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['etl_run_id'], ['etl_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eh_id')
    )
    op.create_table('pretreatment_setup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('etl_run_id', sa.Integer(), nullable=True),
    sa.Column('lineage_group_id', sa.Integer(), nullable=True),
    sa.Column('pretreatment_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pretreatment_exper_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pretreatment_exper_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prepared_samples', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decon_method_id', sa.Integer(), nullable=True),
    sa.Column('decon_vessel_id', sa.Integer(), nullable=True),
    sa.Column('eh_method_id', sa.Integer(), nullable=True),
    sa.Column('experiment_date', sa.Date(), nullable=True),
    sa.Column('experiment_setup_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('analyst_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pretr_url_batch_record', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pretr_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['decon_method_id'], ['method.id'], ),
    sa.ForeignKeyConstraint(['decon_vessel_id'], ['decon_vessel.id'], ),
    sa.ForeignKeyConstraint(['eh_method_id'], ['method.id'], ),
    sa.ForeignKeyConstraint(['etl_run_id'], ['etl_run.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pretreatment_exper_id')
    )
    op.add_column('fermentation_record', sa.Column('pretreatment_setup_id', sa.Integer(), nullable=True))
    op.add_column('fermentation_record', sa.Column('eh_method_id_new', sa.Integer(), nullable=True))
    op.create_foreign_key('fermentation_record_eh_method_id_new_fkey', 'fermentation_record', 'enz_hydr_method', ['eh_method_id_new'], ['id'])
    op.create_foreign_key('fermentation_record_pretreatment_setup_id_fkey', 'fermentation_record', 'pretreatment_setup', ['pretreatment_setup_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fermentation_record_pretreatment_setup_id_fkey', 'fermentation_record', type_='foreignkey')
    op.drop_constraint('fermentation_record_eh_method_id_new_fkey', 'fermentation_record', type_='foreignkey')
    op.drop_column('fermentation_record', 'eh_method_id_new')
    op.drop_column('fermentation_record', 'pretreatment_setup_id')
    op.drop_table('pretreatment_setup')
    op.drop_table('enz_hydr_method')
    # ### end Alembic commands ###
