"""update resource_image unique constraint for nulls

Revision ID: 0013
Revises: 0012
Create Date: 2026-05-20 10:02:34.800453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0013'
down_revision: Union[str, Sequence[str], None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('resource_image_name_url_sort_key'), 'resource_image', type_='unique')
    op.create_unique_constraint('resource_image_name_url_sort_key', 'resource_image', ['resource_name', 'image_url', 'sort_order'], postgresql_nulls_not_distinct=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('resource_image_name_url_sort_key', 'resource_image', type_='unique')
    op.create_unique_constraint(op.f('resource_image_name_url_sort_key'), 'resource_image', ['resource_name', 'image_url', 'sort_order'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
