"""update_infrastructure_food_processor_facilities_model

Revision ID: 0014
Revises: 0013
Create Date: 2026-06-01 14:40:57.107747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '0014'
down_revision: Union[str, Sequence[str], None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infrastructure_food_processing_facilities', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('primary_ag_product', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('process_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('byproducts', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('quantities', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('processing_capacity_products', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('processing_capacity_ton_hr', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('general_source_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('CARB_facility_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('air_district', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('EPA_facility_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('NAICS_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('NAICS_code_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('excess_food_estimate_low', sa.Numeric(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('excess_food_estimate_high', sa.Numeric(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('etl_run_id', sa.Integer(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('lineage_group_id', sa.Integer(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('geocode_status', sa.String(), nullable=True, comment="Geocoding status: 'success', 'failed', or None (pending)"))
    op.create_unique_constraint('uq_foodproc_name_addr_city_zip', 'infrastructure_food_processing_facilities', ['name', 'address', 'city', 'zip'])
    op.drop_column('infrastructure_food_processing_facilities', 'master_type')
    op.drop_column('infrastructure_food_processing_facilities', 'join_count')
    op.drop_column('infrastructure_food_processing_facilities', 'company')
    op.drop_column('infrastructure_food_processing_facilities', 'target_fid')
    op.drop_column('infrastructure_food_processing_facilities', 'wkt_geom')
    op.drop_column('infrastructure_food_processing_facilities', 'processing_type')
    op.drop_column('infrastructure_food_processing_facilities', 'subtype')
    op.drop_column('infrastructure_food_processing_facilities', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_foodproc_name_addr_city_zip', 'infrastructure_food_processing_facilities', type_='unique')
    op.add_column('infrastructure_food_processing_facilities', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('subtype', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('processing_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('wkt_geom', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('target_fid', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('join_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('infrastructure_food_processing_facilities', sa.Column('master_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('infrastructure_food_processing_facilities', 'geocode_status')
    op.drop_column('infrastructure_food_processing_facilities', 'excess_food_estimate_high')
    op.drop_column('infrastructure_food_processing_facilities', 'excess_food_estimate_low')
    op.drop_column('infrastructure_food_processing_facilities', 'website')
    op.drop_column('infrastructure_food_processing_facilities', 'phone_number')
    op.drop_column('infrastructure_food_processing_facilities', 'NAICS_code_description')
    op.drop_column('infrastructure_food_processing_facilities', 'NAICS_code')
    op.drop_column('infrastructure_food_processing_facilities', 'EPA_facility_id')
    op.drop_column('infrastructure_food_processing_facilities', 'air_district')
    op.drop_column('infrastructure_food_processing_facilities', 'CARB_facility_id')
    op.drop_column('infrastructure_food_processing_facilities', 'source_url')
    op.drop_column('infrastructure_food_processing_facilities', 'general_source_info')
    op.drop_column('infrastructure_food_processing_facilities', 'processing_capacity_ton_hr')
    op.drop_column('infrastructure_food_processing_facilities', 'processing_capacity_products')
    op.drop_column('infrastructure_food_processing_facilities', 'quantities')
    op.drop_column('infrastructure_food_processing_facilities', 'byproducts')
    op.drop_column('infrastructure_food_processing_facilities', 'process_type')
    op.drop_column('infrastructure_food_processing_facilities', 'primary_ag_product')
    op.drop_column('infrastructure_food_processing_facilities', 'name')
    op.drop_column('infrastructure_food_processing_facilities', 'lineage_group_id')
    op.drop_column('infrastructure_food_processing_facilities', 'etl_run_id')
    op.drop_column('infrastructure_food_processing_facilities', 'updated_at')
    op.drop_column('infrastructure_food_processing_facilities', 'created_at')
    # ### end Alembic commands ###
