"""normalize infrastructure address columns

Revision ID: 0023
Revises: 0022
Create Date: 2026-05-20 23:52:51.451001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '0023'
down_revision: Union[str, Sequence[str], None] = '0022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infrastructure_biodiesel_plants', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'infrastructure_biodiesel_plants', 'location_address', ['address_id'], ['id'])
    op.drop_column('infrastructure_biodiesel_plants', 'address')
    op.drop_column('infrastructure_petroleum_pipelines', 'lineage_group_id')
    op.drop_column('infrastructure_petroleum_pipelines', 'etl_run_id')
    # ### end Alembic commands ###

    # -------------------------------------------------------------------------
    # Infrastructure address normalization:
    # Drop raw address string columns, add address_id FK + timestamps
    # to all infrastructure tables that lacked them.
    # -------------------------------------------------------------------------

    # -- infrastructure_biosolids_facilities --
    op.drop_column('infrastructure_biosolids_facilities', 'facility_address')
    op.drop_column('infrastructure_biosolids_facilities', 'facility_city')
    op.drop_column('infrastructure_biosolids_facilities', 'state')
    op.drop_column('infrastructure_biosolids_facilities', 'facility_zip')
    op.drop_column('infrastructure_biosolids_facilities', 'facility_county')
    op.drop_column('infrastructure_biosolids_facilities', 'mailing_street_1')
    op.drop_column('infrastructure_biosolids_facilities', 'mailing_city')
    op.drop_column('infrastructure_biosolids_facilities', 'mailing_state')
    op.drop_column('infrastructure_biosolids_facilities', 'mailing_zip')
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_cafo_manure_locations --
    op.drop_column('infrastructure_cafo_manure_locations', 'address')
    op.drop_column('infrastructure_cafo_manure_locations', 'town')
    op.drop_column('infrastructure_cafo_manure_locations', 'state')
    op.drop_column('infrastructure_cafo_manure_locations', 'zip')
    op.add_column('infrastructure_cafo_manure_locations',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_cafo_manure_locations',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_cafo_manure_locations',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_combustion_plants --
    op.drop_column('infrastructure_combustion_plants', 'city')
    op.drop_column('infrastructure_combustion_plants', 'county')
    op.add_column('infrastructure_combustion_plants',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_combustion_plants',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_combustion_plants',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_district_energy_systems --
    op.drop_column('infrastructure_district_energy_systems', 'city')
    op.drop_column('infrastructure_district_energy_systems', 'state')
    op.add_column('infrastructure_district_energy_systems',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_district_energy_systems',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_district_energy_systems',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_ethanol_biorefineries --
    op.drop_column('infrastructure_ethanol_biorefineries', 'address')
    op.drop_column('infrastructure_ethanol_biorefineries', 'city')
    op.drop_column('infrastructure_ethanol_biorefineries', 'state')
    op.add_column('infrastructure_ethanol_biorefineries',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_ethanol_biorefineries',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_ethanol_biorefineries',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_food_processing_facilities --
    op.drop_column('infrastructure_food_processing_facilities', 'address')
    op.drop_column('infrastructure_food_processing_facilities', 'county')
    op.drop_column('infrastructure_food_processing_facilities', 'city')
    op.drop_column('infrastructure_food_processing_facilities', 'state')
    op.drop_column('infrastructure_food_processing_facilities', 'zip')
    op.add_column('infrastructure_food_processing_facilities',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_food_processing_facilities',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_landfills --
    op.drop_column('infrastructure_landfills', 'physical_address')
    op.drop_column('infrastructure_landfills', 'city')
    op.drop_column('infrastructure_landfills', 'county')
    op.drop_column('infrastructure_landfills', 'state')
    op.drop_column('infrastructure_landfills', 'zip_code')
    op.add_column('infrastructure_landfills',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_landfills',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_landfills',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('infrastructure_landfills', 'landfill_opened_year',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using="landfill_opened_year::text::integer")
    op.alter_column('infrastructure_landfills', 'landfill_closure_year',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using="landfill_closure_year::text::integer")

    # -- infrastructure_livestock_anaerobic_digesters --
    op.drop_column('infrastructure_livestock_anaerobic_digesters', 'city')
    op.drop_column('infrastructure_livestock_anaerobic_digesters', 'state')
    op.add_column('infrastructure_livestock_anaerobic_digesters',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_livestock_anaerobic_digesters',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_livestock_anaerobic_digesters',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_msw_to_energy_anaerobic_digesters --
    op.drop_column('infrastructure_msw_to_energy_anaerobic_digesters', 'city')
    op.drop_column('infrastructure_msw_to_energy_anaerobic_digesters', 'county')
    op.add_column('infrastructure_msw_to_energy_anaerobic_digesters',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_msw_to_energy_anaerobic_digesters',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_msw_to_energy_anaerobic_digesters',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_saf_and_renewable_diesel_plants --
    op.drop_column('infrastructure_saf_and_renewable_diesel_plants', 'address')
    op.drop_column('infrastructure_saf_and_renewable_diesel_plants', 'city')
    op.drop_column('infrastructure_saf_and_renewable_diesel_plants', 'state')
    op.drop_column('infrastructure_saf_and_renewable_diesel_plants', 'country')
    op.add_column('infrastructure_saf_and_renewable_diesel_plants',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_saf_and_renewable_diesel_plants',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_saf_and_renewable_diesel_plants',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_wastewater_treatment_plants --
    op.drop_column('infrastructure_wastewater_treatment_plants', 'city')
    op.drop_column('infrastructure_wastewater_treatment_plants', 'county')
    op.drop_column('infrastructure_wastewater_treatment_plants', 'state')
    op.drop_column('infrastructure_wastewater_treatment_plants', 'zipcode')
    op.add_column('infrastructure_wastewater_treatment_plants',
                  sa.Column('address_id', sa.Integer(),
                            sa.ForeignKey('location_address.id'), nullable=True))
    op.add_column('infrastructure_wastewater_treatment_plants',
                  sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('infrastructure_wastewater_treatment_plants',
                  sa.Column('updated_at', sa.DateTime(), nullable=True))

    # -- infrastructure_crude_oil_pipelines --
    op.create_table('infrastructure_crude_oil_pipelines',
        sa.Column('object_id', sa.Integer(), nullable=False),
        sa.Column('operator_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('pipeline_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('pipeline_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('artificial', sa.Integer(), nullable=True),
        sa.Column('master_oid', sa.Numeric(), nullable=True),
        sa.Column('commodity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('volume', sa.Numeric(), nullable=True),
        sa.Column('capacity', sa.Numeric(), nullable=True),
        sa.Column('vcr', sa.Numeric(), nullable=True),
        sa.Column('shape_length', sa.Numeric(), nullable=True),
        sa.Column('mode_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('length', sa.Numeric(), nullable=True),
        sa.Column('geom', geoalchemy2.types.Geometry("MULTILINESTRING"), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('etl_run_id', sa.Integer(), nullable=True),
        sa.Column('lineage_group_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('object_id'),
    )

    # -- infrastructure_railways --
    op.create_table('infrastructure_railways',
        sa.Column('object_id', sa.Integer(), nullable=False),
        sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('link_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('dir_flag', sa.Numeric(), nullable=True),
        sa.Column('volume', sa.Numeric(), nullable=True),
        sa.Column('capacity', sa.Numeric(), nullable=True),
        sa.Column('vcr', sa.Numeric(), nullable=True),
        sa.Column('artificial', sa.Integer(), nullable=True),
        sa.Column('shape_length', sa.Numeric(), nullable=True),
        sa.Column('mode_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('length', sa.Numeric(), nullable=True),
        sa.Column('geom', geoalchemy2.types.Geometry("MULTILINESTRING"), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('etl_run_id', sa.Integer(), nullable=True),
        sa.Column('lineage_group_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('object_id'),
    )

    # -- infrastructure_food_manufacturers_epa --
    op.create_table("infrastructure_food_manufacturers_epa",
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('manufacturer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('naics_code_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('naics_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('excess_food_estimate_low_tons_per_year', sa.Numeric(), nullable=True),
        sa.Column('excess_food_estimate_high_tons_per_year', sa.Numeric(), nullable=True),
        sa.Column('address_id', sa.Integer(), sa.ForeignKey('location_address.id'), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('etl_run_id', sa.Integer(), nullable=True),
        sa.Column('lineage_group_id', sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint('manufacturer_id'),)

    # -- infrastructure_food_manufacturers_carb --
    op.create_table("infrastructure_food_manufacturers_carb",
            sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('processing_facility_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('primary_ag_product', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('process_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('byproducts', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('quantities', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('general_source_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('air_district', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('carb_facility_id', sa.Integer(), nullable=True),
            sa.Column('address_id', sa.Integer(), sa.ForeignKey('location_address.id'), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.Column('etl_run_id', sa.Integer(), nullable=True),
            sa.Column('lineage_group_id', sa.Integer(), nullable=True),
            sa.PrimaryKeyConstraint('processing_facility_id'),)

    # -- infrastructure_tomato_processors --
    op.create_table("infrastructure_tomato_processors",
            sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('processing_facility_id', sa.Integer(), nullable=True),
            sa.Column('processing_capacity_for_tomato_paste_tons_hr', sa.Integer(), nullable=True),
            sa.Column('processing_capacity_of_peeled_chopped_tons_hr', sa.Numeric(), nullable=True),
            sa.Column('mold_metric_tons_yr', sa.Integer(), nullable=True),
            sa.Column('green_metric_tons_yr', sa.Integer(), nullable=True),
            sa.Column('vines_metric_tons_yr', sa.Integer(), nullable=True),
            sa.Column('pomace_metric_tons_yr', sa.Integer(), nullable=True),
            sa.Column('pomace_peels_metric_tons_yr', sa.Integer(), nullable=True),
            sa.Column('pomace_seeds_metric_tons_yr', sa.Integer(), nullable=True),
            sa.Column('peels_only_metric_tons_yr', sa.Integer(), nullable=True),
            sa.Column('seeds_metric_tons_yr', sa.Integer(), nullable=True),
            sa.Column('paste_data_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('chopped_data_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('reliability_of_chopped_data', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
            sa.Column('address_id', sa.Integer(), sa.ForeignKey('location_address.id'), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.Column('etl_run_id', sa.Integer(), nullable=True),
            sa.Column('lineage_group_id', sa.Integer(), nullable=True),
            sa.PrimaryKeyConstraint('processing_facility_id'),)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('infrastructure_petroleum_pipelines', sa.Column('etl_run_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('infrastructure_petroleum_pipelines', sa.Column('lineage_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('infrastructure_biodiesel_plants', sa.Column('address', sa.VARCHAR(), nullable=True))
    # Drop the FK constraint added in upgrade; name was auto-generated by Alembic
    # using the default naming convention: fk_<table>_<col>_<ref_table>
    op.drop_constraint(
        'fk_infrastructure_biodiesel_plants_address_id_location_address',
        'infrastructure_biodiesel_plants',
        type_='foreignkey',
    )
    op.drop_column('infrastructure_biodiesel_plants', 'address_id')
    # ### end Alembic commands ###

    # -------------------------------------------------------------------------
    # Reverse infrastructure address normalization
    # -------------------------------------------------------------------------

    # -- infrastructure_biosolids_facilities --
    op.drop_column('infrastructure_biosolids_facilities', 'address_id')
    op.drop_column('infrastructure_biosolids_facilities', 'created_at')
    op.drop_column('infrastructure_biosolids_facilities', 'updated_at')
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('facility_address', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('facility_city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('state', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('facility_zip', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('facility_county', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('mailing_street_1', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('mailing_city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('mailing_state', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_biosolids_facilities',
                  sa.Column('mailing_zip', sa.VARCHAR(), nullable=True))

    # -- infrastructure_cafo_manure_locations --
    op.drop_column('infrastructure_cafo_manure_locations', 'address_id')
    op.drop_column('infrastructure_cafo_manure_locations', 'created_at')
    op.drop_column('infrastructure_cafo_manure_locations', 'updated_at')
    op.add_column('infrastructure_cafo_manure_locations',
                  sa.Column('address', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_cafo_manure_locations',
                  sa.Column('town', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_cafo_manure_locations',
                  sa.Column('state', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_cafo_manure_locations',
                  sa.Column('zip', sa.VARCHAR(), nullable=True))

    # -- infrastructure_combustion_plants --
    op.drop_column('infrastructure_combustion_plants', 'address_id')
    op.drop_column('infrastructure_combustion_plants', 'created_at')
    op.drop_column('infrastructure_combustion_plants', 'updated_at')
    op.add_column('infrastructure_combustion_plants',
                  sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_combustion_plants',
                  sa.Column('county', sa.VARCHAR(), nullable=True))

    # -- infrastructure_district_energy_systems --
    op.drop_column('infrastructure_district_energy_systems', 'address_id')
    op.drop_column('infrastructure_district_energy_systems', 'created_at')
    op.drop_column('infrastructure_district_energy_systems', 'updated_at')
    op.add_column('infrastructure_district_energy_systems',
                  sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_district_energy_systems',
                  sa.Column('state', sa.VARCHAR(), nullable=True))

    # -- infrastructure_ethanol_biorefineries --
    op.drop_column('infrastructure_ethanol_biorefineries', 'address_id')
    op.drop_column('infrastructure_ethanol_biorefineries', 'created_at')
    op.drop_column('infrastructure_ethanol_biorefineries', 'updated_at')
    op.add_column('infrastructure_ethanol_biorefineries',
                  sa.Column('address', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_ethanol_biorefineries',
                  sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_ethanol_biorefineries',
                  sa.Column('state', sa.VARCHAR(), nullable=True))

    # -- infrastructure_food_processing_facilities --
    op.drop_column('infrastructure_food_processing_facilities', 'address_id')
    op.drop_column('infrastructure_food_processing_facilities', 'created_at')
    op.drop_column('infrastructure_food_processing_facilities', 'updated_at')
    op.add_column('infrastructure_food_processing_facilities',
                  sa.Column('address', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities',
                  sa.Column('county', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities',
                  sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_food_processing_facilities',
                  sa.Column('state', sa.VARCHAR(), nullable=True))

    # -- infrastructure_landfills --
    op.drop_column('infrastructure_landfills', 'address_id')
    op.drop_column('infrastructure_landfills', 'created_at')
    op.drop_column('infrastructure_landfills', 'updated_at')
    op.add_column('infrastructure_landfills',
                  sa.Column('physical_address', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_landfills',
                  sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_landfills',
                  sa.Column('county', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_landfills',
                  sa.Column('state', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_landfills',
                  sa.Column('zip_code', sa.VARCHAR(), nullable=True))
    op.alter_column('infrastructure_landfills', 'landfill_opened_year',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=True,
               postgresql_using="landfill_opened_year::text::date")
    op.alter_column('infrastructure_landfills', 'landfill_closure_year',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=True,
               postgresql_using="landfill_closure_year::text::date")

    # -- infrastructure_livestock_anaerobic_digesters --
    op.drop_column('infrastructure_livestock_anaerobic_digesters', 'address_id')
    op.drop_column('infrastructure_livestock_anaerobic_digesters', 'created_at')
    op.drop_column('infrastructure_livestock_anaerobic_digesters', 'updated_at')
    op.add_column('infrastructure_livestock_anaerobic_digesters',
                  sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_livestock_anaerobic_digesters',
                  sa.Column('state', sa.VARCHAR(), nullable=True))

    # -- infrastructure_msw_to_energy_anaerobic_digesters --
    op.drop_column('infrastructure_msw_to_energy_anaerobic_digesters', 'address_id')
    op.drop_column('infrastructure_msw_to_energy_anaerobic_digesters', 'created_at')
    op.drop_column('infrastructure_msw_to_energy_anaerobic_digesters', 'updated_at')
    op.add_column('infrastructure_msw_to_energy_anaerobic_digesters',
                  sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_msw_to_energy_anaerobic_digesters',
                  sa.Column('county', sa.VARCHAR(), nullable=True))

    # -- infrastructure_saf_and_renewable_diesel_plants --
    op.drop_column('infrastructure_saf_and_renewable_diesel_plants', 'address_id')
    op.drop_column('infrastructure_saf_and_renewable_diesel_plants', 'created_at')
    op.drop_column('infrastructure_saf_and_renewable_diesel_plants', 'updated_at')
    op.add_column('infrastructure_saf_and_renewable_diesel_plants',
                  sa.Column('address', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_saf_and_renewable_diesel_plants',
                  sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_saf_and_renewable_diesel_plants',
                  sa.Column('state', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_saf_and_renewable_diesel_plants',
                  sa.Column('country', sa.VARCHAR(), nullable=True))

    # -- infrastructure_wastewater_treatment_plants --
    op.drop_column('infrastructure_wastewater_treatment_plants', 'address_id')
    op.drop_column('infrastructure_wastewater_treatment_plants', 'created_at')
    op.drop_column('infrastructure_wastewater_treatment_plants', 'updated_at')
    op.add_column('infrastructure_wastewater_treatment_plants',
                  sa.Column('city', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_wastewater_treatment_plants',
                  sa.Column('county', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_wastewater_treatment_plants',
                  sa.Column('state', sa.VARCHAR(), nullable=True))
    op.add_column('infrastructure_wastewater_treatment_plants',
                  sa.Column('zipcode', sa.VARCHAR(), nullable=True))
    op.drop_table('infrastructure_crude_oil_pipelines')
    op.drop_table('infrastructure_railways')
    op.drop_table('infrastructure_food_manufacturers_epa')
    op.drop_table('infrastructure_food_manufacturers_carb')
    op.drop_table('infrastructure_ttomato_processors')
