# audit/skills/executive_summary.py
"""
Generates the single executive_audit_summary.md from all target results.
"""
from datetime import datetime
from pathlib import Path
from typing import List, Dict
from audit.skills.llm_synthesis import SynthesisResult

def generate_executive_summary(
    target_results: List[Dict],  # [{target_name, synthesis, flagged_count, evidently_html_path}]
    output_dir: Path,
    sheet_url: str = "",
) -> Path:
    """
    Writes executive_audit_summary.md to output_dir.
    Returns the path to the written file.
    """
    date_str = datetime.now().strftime("%Y-%m-%d")
    lines = [
        f"# 📊 Data Quality Executive Summary — {date_str}\n",
        f"> Generated by the CA Biositing Audit Platform\n",
    ]
    if sheet_url:
        lines.append(f"> **[🔗 Anomaly Tracker (Google Sheets)]({sheet_url})**\n")
    lines.append("\n---\n")

    # Overall stats
    total_issues = sum(
        len(r["synthesis"].grouped_issues) for r in target_results
        if r.get("synthesis")
    )
    high_issues = sum(
        len([i for i in r["synthesis"].grouped_issues if i.priority == "High"])
        for r in target_results if r.get("synthesis")
    )
    lines.append(f"## 🔢 Overall: {total_issues} grouped issues ({high_issues} High priority)\n\n")

    for result in target_results:
        target_name = result["target_name"]
        synthesis: SynthesisResult = result.get("synthesis")
        flagged_count = result.get("flagged_count", 0)
        evidently_path = result.get("evidently_html_path", "")

        lines.append(f"## Target: `{target_name}`\n")
        lines.append(f"**Flagged observations:** {flagged_count}\n\n")

        if evidently_path:
            lines.append(f"**[📈 Evidently Profile]({evidently_path})**\n\n")

        if synthesis:
            lines.append("### Executive Summary\n")
            lines.append(synthesis.executive_summary + "\n\n")
            lines.append("### Grouped Issues\n\n")
            lines.append("| Priority | Group | Hypothesis | Action |\n")
            lines.append("|----------|-------|------------|--------|\n")
            for issue in sorted(synthesis.grouped_issues, key=lambda x: ["High","Medium","Low"].index(x.priority)):
                lines.append(
                    f"| {issue.priority} | {issue.group_label} | "
                    f"{issue.hypothesis[:80]}... | {issue.recommended_action[:60]}... |\n"
                )
        lines.append("\n---\n")

    summary_path = output_dir / "executive_audit_summary.md"
    summary_path.write_text("".join(lines))
    return summary_path
