project:
  type: website
  output-dir: _site

website:
  title: "BioCirV Data Quality Portal"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
